package dev.kuml.plugin.examples.pdf

import dev.kuml.core.model.KumlModel
import dev.kuml.plugin.api.core.KumlVersionRange
import dev.kuml.plugin.api.core.PluginCapability
import dev.kuml.plugin.api.core.PluginDescriptor
import dev.kuml.plugin.api.core.PluginVersion
import dev.kuml.plugin.api.renderer.KumlRendererPlugin
import dev.kuml.plugin.api.renderer.RendererCapabilities
import org.apache.pdfbox.pdmodel.PDDocument
import org.apache.pdfbox.pdmodel.PDPage
import org.apache.pdfbox.pdmodel.PDPageContentStream
import org.apache.pdfbox.pdmodel.common.PDRectangle
import org.apache.pdfbox.pdmodel.font.PDType1Font
import org.apache.pdfbox.pdmodel.font.Standard14Fonts
import java.io.ByteArrayOutputStream

/**
 * PDF Renderer Plugin — renders kUML models to single-page PDFs via Apache PDFBox 3.x.
 *
 * V3.0.32 MVP: produces a titled placeholder PDF with model name.
 * Full SVG→PDF vector embedding is deferred to V3.1 (requires SVG→PDF bridge).
 */
public class PdfRendererPlugin : KumlRendererPlugin {
    override val descriptor: PluginDescriptor =
        PluginDescriptor(
            id = "dev.kuml.plugin.renderer.pdf",
            name = "PDF Renderer",
            version = PluginVersion(1, 0, 0),
            kumlVersionRange = KumlVersionRange(">=0.12.0"),
            capabilities = setOf(PluginCapability.RENDERER),
            // No special permissions — rendering is pure computation
        )

    override val renderCapabilities: RendererCapabilities =
        RendererCapabilities(
            supportedFormats = setOf("pdf"),
            supportedDiagramTypes = setOf("*"),
        )

    override fun render(
        model: KumlModel,
        format: String,
        options: Map<String, String>,
    ): ByteArray {
        require(format == "pdf") { "Unsupported format: $format" }

        val document = PDDocument()
        val page = PDPage(PDRectangle.A4)
        document.addPage(page)

        PDPageContentStream(document, page).use { cs ->
            val titleFont = PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD)
            cs.beginText()
            cs.setFont(titleFont, 18f)
            cs.newLineAtOffset(50f, page.mediaBox.height - 80f)
            cs.showText("kUML Diagram: ${model.name}")
            cs.endText()

            val bodyFont = PDType1Font(Standard14Fonts.FontName.HELVETICA)
            cs.beginText()
            cs.setFont(bodyFont, 12f)
            cs.newLineAtOffset(50f, page.mediaBox.height - 120f)
            cs.showText("Language: ${model.language}   Level: ${model.level}")
            cs.endText()

            cs.beginText()
            cs.setFont(bodyFont, 10f)
            cs.newLineAtOffset(50f, page.mediaBox.height - 160f)
            cs.showText("Generated by kUML plugin-renderer-pdf v1.0.0")
            cs.endText()
        }

        val out = ByteArrayOutputStream()
        document.save(out)
        document.close()
        return out.toByteArray()
    }
}
