package dev.kuml.codegen.sql

import dev.kuml.codegen.api.CodeGenerationException
import dev.kuml.core.model.KumlMetaValue
import dev.kuml.erm.constraint.ErmConstraintChecker
import dev.kuml.erm.constraint.ViolationSeverity
import dev.kuml.erm.model.ErmAttribute
import dev.kuml.erm.model.ErmEntity
import dev.kuml.erm.model.ErmMetadataKeys
import dev.kuml.erm.model.ErmModel
import dev.kuml.erm.model.ReferentialAction

/**
 * V3.4.7 — the single source of truth for SQL DDL generation from an
 * [ErmModel]. Both entry points ([SqlDdlGenerator]'s UML-direct chain and
 * [ErmSqlDdlGenerator]'s ERM-first path) delegate here; neither contains any
 * DDL-rendering logic of its own.
 *
 * Emission pipeline (see [emit]):
 *  1. Validate the model with [ErmConstraintChecker] — any `ERROR`-severity
 *     violation fails generation with [CodeGenerationException] instead of
 *     emitting structurally broken DDL. This is a deliberate *second*
 *     validation for the UML-direct path (`UmlToErmTransformer` already
 *     validates once) — cheap and harmless there, but the only gate at all
 *     for the ERM-first path, which never goes through the transformer.
 *  2. Header comment.
 *  3. Optional `DROP VIEW`/`DROP TABLE` block (reverse dependency order).
 *  4. `CREATE TABLE` per entity, in topological (dependency-respecting) order.
 *  5. `ALTER TABLE … ADD CONSTRAINT … FOREIGN KEY …` block.
 *  6. `CREATE [UNIQUE] INDEX` block.
 *  7. `CREATE VIEW` block.
 */
internal class ErmSqlEmitter(
    private val dialect: SqlDialect,
    private val options: SqlEmitOptions,
) {
    fun emit(model: ErmModel): String {
        val errors = ErmConstraintChecker().check(model).filter { it.severity == ViolationSeverity.ERROR }
        if (errors.isNotEmpty()) {
            throw CodeGenerationException(
                "kuml-gen-sql: ERM model '${model.name}' failed validation — refusing to emit DDL:\n" +
                    errors.joinToString("\n") { "  - ${it.message}" },
            )
        }

        val sorted = topologicalSort(model)
        val sb = StringBuilder()

        if (options.schemaComment) {
            sb.appendLine("-- Generated by kUML — schema for \"${model.name}\"")
            sb.appendLine("-- Dialect: ${dialect.key}")
            sb.appendLine()
        }

        if (options.withDrop) {
            sb.append(renderDropBlock(model, sorted))
        }

        for (entity in sorted) sb.append(renderCreateTable(entity))

        // TimescaleDB hypertables must be declared on the freshly-created, still-empty table,
        // before secondary indexes — hence between CREATE TABLE and the FK/index/view blocks.
        sb.append(renderHypertables(model))

        sb.append(renderForeignKeys(model))
        sb.append(renderIndexes(model))
        sb.append(renderViews(model))

        return sb.toString()
    }

    // ── DROP block ───────────────────────────────────────────────────────────

    private fun renderDropBlock(
        model: ErmModel,
        sorted: List<ErmEntity>,
    ): String {
        val sb = StringBuilder()
        if (model.views.isNotEmpty()) {
            sb.appendLine("-- DROP VIEWs")
            for (view in model.views) {
                sb.appendLine("DROP VIEW IF EXISTS ${viewNameOf(view.name, view.id)};")
            }
            sb.appendLine()
        }
        sb.appendLine("-- DROP TABLEs (reverse dependency order)")
        for (entity in sorted.reversed()) {
            sb.appendLine("DROP TABLE IF EXISTS ${tableNameOf(entity)};")
        }
        sb.appendLine()
        return sb.toString()
    }

    // ── CREATE TABLE ─────────────────────────────────────────────────────────

    private fun renderCreateTable(entity: ErmEntity): String {
        val tableName = tableNameOf(entity)
        val singleColumnPk = entity.primaryKey.size == 1

        val lines = entity.attributes.map { renderColumn(it, singleColumnPk) } + renderTableConstraints(entity)

        val sb = StringBuilder()
        sb.appendLine("CREATE TABLE $tableName (")
        sb.append(lines.joinToString(",\n"))
        sb.appendLine()
        sb.appendLine(");")
        sb.appendLine()
        return sb.toString()
    }

    private fun renderColumn(
        attr: ErmAttribute,
        singleColumnPk: Boolean,
    ): String {
        val colName = columnNameOf(attr)
        val colType = ErmSqlTypeMapper.columnType(attr, dialect)

        val parts = mutableListOf("$colName $colType")

        // SERIAL/BIGSERIAL/AUTO_INCREMENT columns are implicitly NOT NULL and cannot carry
        // a separate DEFAULT — stolperfalle 5 in the V3.4.7 plan. Skip both clauses then.
        if (!attr.autoIncrement) {
            parts += if (attr.nullable) "NULL" else "NOT NULL"
            if (attr.unique && !attr.primaryKey) parts += "UNIQUE"
            attr.default?.let { parts += "DEFAULT $it" }
        }
        if (attr.primaryKey && singleColumnPk) parts += "PRIMARY KEY"

        return "    " + parts.joinToString(" ")
    }

    private fun renderTableConstraints(entity: ErmEntity): List<String> {
        val lines = mutableListOf<String>()
        if (entity.primaryKey.size > 1) {
            val cols = entity.primaryKey.joinToString(", ") { columnNameOf(it) }
            lines += "    PRIMARY KEY ($cols)"
        }
        entity.checks.forEach { check ->
            val prefix = check.name?.let { "CONSTRAINT ${checkNameOf(it, check.id)} " } ?: ""
            lines += "    ${prefix}CHECK (${check.expression})"
        }
        return lines
    }

    // ── TimescaleDB hypertables (ADR-0016 §2.3) ─────────────────────────────────

    /**
     * Emits `SELECT create_hypertable(...)` for every entity carrying an
     * [ErmMetadataKeys.HYPERTABLE] metadata marker. Postgres-only: TimescaleDB is a
     * Postgres extension, so every other dialect returns an empty string unconditionally,
     * regardless of whether the marker is present.
     */
    private fun renderHypertables(model: ErmModel): String {
        if (dialect != SqlDialect.POSTGRES) return ""

        val sb = StringBuilder()
        var any = false
        for (entity in model.entities) {
            val entries = (entity.metadata[ErmMetadataKeys.HYPERTABLE] as? KumlMetaValue.Entries)?.value ?: continue
            val timeColName =
                (entries[ErmMetadataKeys.HT_TIME_COLUMN] as? KumlMetaValue.Text)?.value
                    ?: throw CodeGenerationException(
                        "kuml-gen-sql: hypertable marker on entity '${entity.name ?: entity.id}' is missing " +
                            "the required '${ErmMetadataKeys.HT_TIME_COLUMN}' entry.",
                    )
            val timeAttr =
                entity.attributeByName(timeColName)
                    ?: throw CodeGenerationException(
                        "kuml-gen-sql: hypertable time column '$timeColName' declared on entity " +
                            "'${entity.name ?: entity.id}' does not exist on that entity.",
                    )

            val table = tableNameOf(entity)
            val col = columnNameOf(timeAttr)
            val interval =
                (entries[ErmMetadataKeys.HT_CHUNK_INTERVAL] as? KumlMetaValue.Text)
                    ?.value
                    ?.let { requireSafeInterval(it, entity.id) }

            if (!any) {
                sb.appendLine("-- TimescaleDB hypertables")
                sb.appendLine()
                any = true
            }
            val chunkArg = interval?.let { ", chunk_time_interval => INTERVAL '$it'" } ?: ""
            sb.appendLine("SELECT create_hypertable('$table', '$col', if_not_exists => TRUE$chunkArg);")
        }
        if (any) sb.appendLine()
        return sb.toString()
    }

    /**
     * Whitelist guard for the [ErmMetadataKeys.HT_CHUNK_INTERVAL] free-text value — the only
     * user-supplied string that lands inside a SQL string literal (`INTERVAL '...'`) in the
     * hypertable block. Table/column names go through [SqlNames.requireSafe] as identifiers
     * instead; this value is a literal, so it needs its own injection guard.
     */
    private fun requireSafeInterval(
        interval: String,
        entityId: String,
    ): String {
        if (!SAFE_INTERVAL_REGEX.matches(interval)) {
            throw CodeGenerationException(
                "kuml-gen-sql: hypertable chunkInterval '$interval' (entity '$entityId') is not a safe " +
                    "Postgres INTERVAL literal — expected e.g. '7 days', refusing to emit DDL.",
            )
        }
        return interval
    }

    // ── Foreign Keys ─────────────────────────────────────────────────────────

    private fun renderForeignKeys(model: ErmModel): String {
        val sb = StringBuilder()
        var any = false
        for (entity in model.entities) {
            for (attr in entity.attributes) {
                val fk = attr.foreignKey ?: continue
                val targetEntity = model.entityById(fk.targetEntityId) ?: continue
                if (!any) {
                    sb.appendLine("-- Foreign Keys")
                    sb.appendLine()
                    any = true
                }

                val fkTable = tableNameOf(entity)
                val fkColumn = columnNameOf(attr)
                val refTable = tableNameOf(targetEntity)
                val targetAttr =
                    fk.targetAttributeId?.let { id -> targetEntity.attributes.firstOrNull { it.id == id } }
                        ?: targetEntity.primaryKey.singleOrNull()
                val refColumn = targetAttr?.let { columnNameOf(it) } ?: "id"

                val constraintName = SqlNames.requireSafe("fk_${fkTable}_$fkColumn", "FK constraint name", attr.id)
                val onDelete = referentialClause("ON DELETE", fk.onDelete)
                val onUpdate = referentialClause("ON UPDATE", fk.onUpdate)

                sb.appendLine(
                    "ALTER TABLE $fkTable ADD CONSTRAINT $constraintName " +
                        "FOREIGN KEY ($fkColumn) REFERENCES $refTable($refColumn)$onDelete$onUpdate;",
                )
            }
        }
        if (any) sb.appendLine()
        return sb.toString()
    }

    private fun referentialClause(
        keyword: String,
        action: ReferentialAction,
    ): String =
        when (action) {
            ReferentialAction.NO_ACTION -> ""
            ReferentialAction.RESTRICT -> " $keyword RESTRICT"
            ReferentialAction.CASCADE -> " $keyword CASCADE"
            ReferentialAction.SET_NULL -> " $keyword SET NULL"
            ReferentialAction.SET_DEFAULT -> " $keyword SET DEFAULT"
        }

    // ── Indexes ──────────────────────────────────────────────────────────────

    private fun renderIndexes(model: ErmModel): String {
        val sb = StringBuilder()
        var any = false
        for (entity in model.entities) {
            if (entity.indexes.isEmpty()) continue
            if (!any) {
                sb.appendLine("-- Indexes")
                sb.appendLine()
                any = true
            }
            val tableName = tableNameOf(entity)
            for (index in entity.indexes) {
                val cols =
                    index.attributeIds
                        .mapNotNull { attrId -> entity.attributes.firstOrNull { it.id == attrId } }
                        .map { columnNameOf(it) }
                val defaultName = "idx_${tableName}_${cols.joinToString("_")}"
                val idxName = SqlNames.requireSafe(index.name ?: defaultName, "index name", index.id)
                val uniqueKeyword = if (index.unique) "UNIQUE " else ""
                sb.appendLine("CREATE ${uniqueKeyword}INDEX $idxName ON $tableName (${cols.joinToString(", ")});")
            }
        }
        if (any) sb.appendLine()
        return sb.toString()
    }

    // ── Views ────────────────────────────────────────────────────────────────

    private fun renderViews(model: ErmModel): String {
        if (model.views.isEmpty()) return ""
        val sb = StringBuilder()
        sb.appendLine("-- Views")
        sb.appendLine()
        for (view in model.views) {
            sb.appendLine("CREATE VIEW ${viewNameOf(view.name, view.id)} AS ${view.query};")
            sb.appendLine()
        }
        return sb.toString()
    }

    // ── Naming / identifier safety ───────────────────────────────────────────

    private fun tableNameOf(entity: ErmEntity): String = SqlNames.requireSafe(entity.name ?: entity.id, "table name", entity.id)

    private fun columnNameOf(attr: ErmAttribute): String = SqlNames.requireSafe(attr.name ?: attr.id, "column name", attr.id)

    private fun viewNameOf(
        name: String?,
        id: String,
    ): String = SqlNames.requireSafe(name ?: id, "view name", id)

    private fun checkNameOf(
        name: String,
        id: String,
    ): String = SqlNames.requireSafe(name, "check constraint name", id)

    // ── Topological sort ─────────────────────────────────────────────────────

    /**
     * Kahn's algorithm over [ErmAttribute.foreignKey] edges: an entity depends on
     * (must be created after) every entity its columns hold a foreign key to.
     * Self-referencing foreign keys are ignored — they never create an ordering
     * constraint. Entities involved in a cycle (only possible via a chain of
     * mutually-referencing FKs) are appended best-effort in declaration order.
     */
    private fun topologicalSort(model: ErmModel): List<ErmEntity> {
        val entities = model.entities
        val byId = entities.associateBy { it.id }
        val inDegree = entities.associate { it.id to 0 }.toMutableMap()
        val edges = mutableMapOf<String, MutableList<String>>()
        entities.forEach { edges[it.id] = mutableListOf() }

        for (entity in entities) {
            for (attr in entity.attributes) {
                val targetId = attr.foreignKey?.targetEntityId ?: continue
                if (targetId == entity.id) continue // self-referencing FK — no ordering edge
                if (targetId !in edges) continue
                edges.getValue(targetId).add(entity.id)
                inDegree[entity.id] = (inDegree[entity.id] ?: 0) + 1
            }
        }

        val queue = ArrayDeque(inDegree.filterValues { it == 0 }.keys.toList())
        val sorted = mutableListOf<ErmEntity>()
        val seen = mutableSetOf<String>()
        while (queue.isNotEmpty()) {
            val id = queue.removeFirst()
            if (id in seen) continue
            seen += id
            byId[id]?.let { sorted += it }
            for (next in edges[id].orEmpty()) {
                inDegree[next] = (inDegree[next] ?: 0) - 1
                if (inDegree[next] == 0) queue += next
            }
        }
        for (entity in entities) if (entity.id !in seen) sorted += entity
        return sorted
    }

    private companion object {
        /** `<digits> <unit>[s]`, e.g. `"7 days"`, `"1 hour"` — whitelist for [requireSafeInterval]. */
        val SAFE_INTERVAL_REGEX =
            Regex(
                """^\d{1,6}\s+(second|minute|hour|day|week|month|year)s?$""",
                RegexOption.IGNORE_CASE,
            )
    }
}

/**
 * Options controlling [ErmSqlEmitter]'s output — parsed from the generic
 * `options: Map<String, String>` both [SqlDdlGenerator] and [ErmSqlDdlGenerator]
 * receive from the CLI/MCP layer.
 */
internal data class SqlEmitOptions(
    val withDrop: Boolean = false,
    val schemaComment: Boolean = true,
) {
    companion object {
        fun from(options: Map<String, String>): SqlEmitOptions =
            SqlEmitOptions(
                withDrop = options["sql-drop"]?.lowercase() == "true",
            )
    }
}
