package dev.kuml.codegen.sql

import dev.kuml.codegen.api.KumlCodeGenerator
import dev.kuml.core.model.KumlDiagram
import dev.kuml.uml.UmlAssociation
import dev.kuml.uml.UmlClass
import dev.kuml.uml.UmlEnumeration
import dev.kuml.uml.UmlGeneralization
import java.io.File

/**
 * V1.1.4 — SQL DDL Generator.
 *
 * Optionen via `options`-Map:
 *  - `sql-dialect` — `postgres` (default) / `mysql` / `h2` / `sqlite`
 *  - `sql-drop`    — `true` für einen führenden `DROP TABLE`-Block (default false)
 *
 * Schreibt eine einzelne Datei `schema.sql` mit topologisch sortierten
 * `CREATE TABLE`-Blöcken und einem `ALTER TABLE … ADD CONSTRAINT`-Block für
 * Foreign Keys am Datei-Ende.
 *
 * Stereotyp-aware: `«Entity»{tableName=…}` setzt den Tabellennamen,
 * `«Column»{name=…}` den Spaltennamen, `«Id»` den Primary Key.
 * `«Transient»`/`«Internal»` schließen Properties aus.
 */
public class SqlDdlGenerator : KumlCodeGenerator {
    override val id: String = "sql"
    override val displayName: String = "SQL DDL (PostgreSQL / MySQL / H2 / SQLite)"

    override fun generate(
        diagram: KumlDiagram,
        outputDir: File,
        options: Map<String, String>,
    ): List<File> {
        outputDir.mkdirs()
        val dialect = SqlDialect.from(options["sql-dialect"] ?: "postgres")
        val withDrop = options["sql-drop"]?.lowercase() == "true"

        val classes = diagram.elements.filterIsInstance<UmlClass>()
        val enums = diagram.elements.filterIsInstance<UmlEnumeration>()
        val associations = diagram.elements.filterIsInstance<UmlAssociation>()
        val generalizations = diagram.elements.filterIsInstance<UmlGeneralization>()

        val sorted = topologicalSort(classes, associations, generalizations)

        val sb = StringBuilder()
        sb.appendLine("-- Generated by kUML — schema for diagram \"${diagram.name}\"")
        sb.appendLine("-- Dialect: ${dialect.key}")
        sb.appendLine()

        // Postgres-only ENUM type declarations come first
        if (dialect == SqlDialect.POSTGRES) {
            for (e in enums) sb.append(renderPostgresEnum(e))
        }

        if (withDrop) {
            sb.appendLine("-- DROP TABLEs (reverse dependency order)")
            for (cls in sorted.reversed()) {
                sb.appendLine(
                    "DROP TABLE IF EXISTS ${SqlNames.tableName(cls.name, cls.appliedStereotypes)};",
                )
            }
            sb.appendLine()
        }

        for (cls in sorted) sb.append(renderCreateTable(cls, dialect))

        sb.append(renderForeignKeys(classes, associations, dialect))

        val file = File(outputDir, "schema.sql")
        file.writeText(sb.toString())
        return listOf(file)
    }

    // ── CREATE TABLE ─────────────────────────────────────────────────────────

    private fun renderCreateTable(
        cls: UmlClass,
        dialect: SqlDialect,
    ): String {
        val tableName = SqlNames.tableName(cls.name, cls.appliedStereotypes)
        val sb = StringBuilder()
        sb.appendLine("CREATE TABLE $tableName (")

        val visibleAttrs =
            cls.attributes.filterNot {
                it.appliedStereotypes.any { st -> st.stereotypeName == "Transient" || st.stereotypeName == "Internal" }
            }
        val hasExplicitId =
            visibleAttrs.any { it.appliedStereotypes.any { s -> s.stereotypeName == "Id" } }
        val columns = mutableListOf<String>()

        if (!hasExplicitId) {
            val pkType =
                when (dialect) {
                    SqlDialect.POSTGRES -> "BIGSERIAL"
                    SqlDialect.MYSQL -> "BIGINT AUTO_INCREMENT"
                    SqlDialect.H2 -> "BIGINT AUTO_INCREMENT"
                    SqlDialect.SQLITE -> "INTEGER"
                }
            columns += "    id $pkType PRIMARY KEY"
        }

        for (attr in visibleAttrs) {
            if (SqlTypeMapper.isManyToManyCandidate(attr.multiplicity)) {
                sb.appendLine("    -- TODO: many-to-many join table for '${attr.name}'")
                continue
            }
            val colName = SqlNames.columnName(attr.name, attr.appliedStereotypes)
            val colType = SqlTypeMapper.toSqlType(attr.type, dialect)
            val nullClause = SqlTypeMapper.nullClause(attr.multiplicity)
            val isPk = attr.appliedStereotypes.any { it.stereotypeName == "Id" }
            val pkSuffix = if (isPk) " PRIMARY KEY" else ""
            columns += "    $colName $colType $nullClause$pkSuffix".trimEnd()
        }

        sb.append(columns.joinToString(",\n"))
        sb.appendLine().appendLine(");").appendLine()
        return sb.toString()
    }

    // ── Foreign Keys ─────────────────────────────────────────────────────────

    private fun renderForeignKeys(
        classes: List<UmlClass>,
        associations: List<UmlAssociation>,
        dialect: SqlDialect,
    ): String {
        if (associations.isEmpty()) return ""
        val sb = StringBuilder()
        sb.appendLine("-- Foreign Keys")
        sb.appendLine()

        val byId: Map<String, UmlClass> = classes.associateBy { it.id }

        for (assoc in associations) {
            if (assoc.ends.size != 2) continue // V1.1.4 supports binary associations only
            val end1 = assoc.ends[0]
            val end2 = assoc.ends[1]
            val class1 = byId[end1.typeId] ?: continue
            val class2 = byId[end2.typeId] ?: continue

            // Skip many-to-many: needs a join table (V1.2)
            val end1Many = end1.multiplicity.upper == null || end1.multiplicity.upper!! > 1
            val end2Many = end2.multiplicity.upper == null || end2.multiplicity.upper!! > 1
            if (end1Many && end2Many) {
                sb.appendLine(
                    "-- TODO: many-to-many join table for ${class1.name} ↔ ${class2.name}",
                )
                sb.appendLine()
                continue
            }

            // FK lives on the "many" side. If both ends are (≤1, ≤1), put FK on end2 by convention.
            val (fkSide, refSide) =
                when {
                    end1Many -> class1 to class2
                    end2Many -> class2 to class1
                    else -> class2 to class1 // 1:1 — pick end2 to host the FK
                }

            val fkTable = SqlNames.tableName(fkSide.name, fkSide.appliedStereotypes)
            val refTable = SqlNames.tableName(refSide.name, refSide.appliedStereotypes)
            val fkColumn = "${refSide.name.lowercase()}_id"
            val constraintName = "fk_${fkTable}_${refSide.name.lowercase()}"

            val bigintType = if (dialect == SqlDialect.SQLITE) "INTEGER" else "BIGINT"
            sb.appendLine("ALTER TABLE $fkTable ADD COLUMN $fkColumn $bigintType;")
            sb.appendLine(
                "ALTER TABLE $fkTable ADD CONSTRAINT $constraintName " +
                    "FOREIGN KEY ($fkColumn) REFERENCES $refTable(id);",
            )
            sb.appendLine()
        }
        return sb.toString()
    }

    // ── Postgres ENUM type ───────────────────────────────────────────────────

    private fun renderPostgresEnum(e: UmlEnumeration): String {
        val literals = e.literals.joinToString(", ") { "'${it.name}'" }
        return "CREATE TYPE ${e.name.lowercase()} AS ENUM ($literals);\n\n"
    }

    // ── Topological sort ─────────────────────────────────────────────────────

    private fun topologicalSort(
        classes: List<UmlClass>,
        associations: List<UmlAssociation>,
        generalizations: List<UmlGeneralization>,
    ): List<UmlClass> {
        val byId = classes.associateBy { it.id }
        val inDegree = classes.associate { it.id to 0 }.toMutableMap()
        val edges = mutableMapOf<String, MutableList<String>>()
        classes.forEach { edges[it.id] = mutableListOf() }

        // Generalization: child depends on parent
        for (gen in generalizations) {
            if (gen.specificId in inDegree && gen.generalId in edges) {
                edges[gen.generalId]?.add(gen.specificId)
                inDegree[gen.specificId] = (inDegree[gen.specificId] ?: 0) + 1
            }
        }
        // Association FK: FK-bearing class depends on the referenced class.
        for (assoc in associations) {
            if (assoc.ends.size != 2) continue
            val end1 = assoc.ends[0]
            val end2 = assoc.ends[1]
            val class1Id = end1.typeId
            val class2Id = end2.typeId
            val end1Many = end1.multiplicity.upper == null || end1.multiplicity.upper!! > 1
            val end2Many = end2.multiplicity.upper == null || end2.multiplicity.upper!! > 1
            if (end1Many && end2Many) continue // many-to-many — no FK in V1.1.4

            val (fkSideId, refSideId) =
                when {
                    end1Many -> class1Id to class2Id
                    end2Many -> class2Id to class1Id
                    else -> class2Id to class1Id
                }
            if (fkSideId !in inDegree || refSideId !in edges) continue
            edges[refSideId]?.add(fkSideId)
            inDegree[fkSideId] = (inDegree[fkSideId] ?: 0) + 1
        }

        val queue = ArrayDeque(inDegree.filterValues { it == 0 }.keys.toList())
        val sorted = mutableListOf<UmlClass>()
        val seen = mutableSetOf<String>()
        while (queue.isNotEmpty()) {
            val id = queue.removeFirst()
            if (id in seen) continue
            seen += id
            byId[id]?.let { sorted += it }
            for (next in edges[id] ?: emptyList()) {
                inDegree[next] = (inDegree[next] ?: 0) - 1
                if (inDegree[next] == 0) queue += next
            }
        }
        // Append classes involved in cycles (best-effort)
        for (cls in classes) if (cls.id !in seen) sorted += cls
        return sorted
    }
}
