package dev.kuml.codegen.m2m.jpa

import dev.kuml.codegen.m2m.GeneratedFile
import dev.kuml.codegen.m2m.KumlTransformer
import dev.kuml.codegen.m2m.KumlTransformerProvider
import dev.kuml.codegen.m2m.TraceabilityLink
import dev.kuml.codegen.m2m.TransformContext
import dev.kuml.codegen.m2m.TransformError
import dev.kuml.codegen.m2m.TransformResult
import dev.kuml.codegen.m2m.TransformTrace
import dev.kuml.core.model.KumlDiagram
import dev.kuml.uml.UmlAssociation
import dev.kuml.uml.UmlClass

/**
 * Transforms a UML class diagram into Kotlin JPA entity source files.
 *
 * For each [UmlClass] in the diagram:
 * - Emits one Kotlin data class annotated with `@Entity` + `@Table`
 * - Each [dev.kuml.uml.UmlProperty] (attribute) becomes a `@Column` property
 * - The attribute named `"id"` (case-insensitive) or with stereotype `«id»`
 *   becomes `@Id @GeneratedValue`
 * - If no id attribute exists, a synthetic `@Id val id: Long = 0L` is generated
 * - Association with multiplicity `upper == null` or `upper > 1` → `@OneToMany`
 * - Association with `upper == 1` → `@ManyToOne` or `@OneToOne`
 * - Stereotype `«transient»` on attribute → `@Transient`
 * - Stereotype `«embedded»` on attribute → `@Embedded`
 *
 * Output: one [GeneratedFile] per [UmlClass], path = `"<ClassName>.kt"`.
 *
 * V2.x deferred: bidirectional `@ManyToMany`, `@MappedSuperclass`,
 * Kotlin-JPA plugin optimizations, `@Embeddable` generation.
 */
public class UmlToJpaTransformer : KumlTransformer<KumlDiagram, List<GeneratedFile>> {
    override val id: String = "uml-to-jpa"
    override val description: String =
        "UML class diagram → Kotlin JPA entity files (@Entity, @Table, @Column, …)"

    override fun transform(
        source: KumlDiagram,
        ctx: TransformContext,
    ): TransformResult<List<GeneratedFile>> {
        val packageName = ctx.options["package"] ?: DEFAULT_PACKAGE
        val errors = mutableListOf<TransformError>()
        val files = mutableListOf<GeneratedFile>()
        var trace = TransformTrace()

        // Build a lookup from element id → UmlClass name (for association targets)
        val classById: Map<String, UmlClass> =
            source.elements.filterIsInstance<UmlClass>().associateBy { it.id }
        val classIdByName: Map<String, String> =
            source.elements.filterIsInstance<UmlClass>().associate { it.name to it.id }

        // Collect associations so we can emit @OneToMany / @ManyToOne on the owning side
        val associations: List<UmlAssociation> = source.elements.filterIsInstance<UmlAssociation>()

        for (cls in classById.values) {
            val result =
                generateEntity(
                    cls = cls,
                    packageName = packageName,
                    classById = classById,
                    classIdByName = classIdByName,
                    associations = associations,
                )
            when (result) {
                is EntityResult.Ok -> {
                    files += result.file
                    trace = trace.plus(TraceabilityLink(cls.id, result.file.relativePath, RULE_CLASS_TO_ENTITY))
                }
                is EntityResult.Error -> errors += result.error
            }
        }

        if (errors.isNotEmpty()) return TransformResult.Failure(errors)
        return TransformResult.Success(files, trace)
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    private sealed class EntityResult {
        data class Ok(
            val file: GeneratedFile,
        ) : EntityResult()

        data class Error(
            val error: TransformError,
        ) : EntityResult()
    }

    private fun generateEntity(
        cls: UmlClass,
        packageName: String,
        classById: Map<String, UmlClass>,
        classIdByName: Map<String, String>,
        associations: List<UmlAssociation>,
    ): EntityResult {
        val tableName = toSnakeCase(cls.name).toPlural()
        val sb = StringBuilder()

        sb.appendLine("// Generated by kuml-codegen-m2m (uml-to-jpa) — do not edit manually.")
        sb.appendLine()
        sb.appendLine("package $packageName")
        sb.appendLine()
        sb.appendLine("import jakarta.persistence.*")
        sb.appendLine()
        sb.appendLine("@Entity")
        sb.appendLine("@Table(name = \"$tableName\")")
        sb.append("data class ${cls.name}(")

        val params = mutableListOf<String>()
        var hasIdAttribute = false

        for (attr in cls.attributes) {
            val attrName = attr.name
            val attrType = jpaKotlinType(attr.type.name)
            val attrDefault = jpaDefaultValue(attr.type.name)
            val colName = toSnakeCase(attrName)
            val stereotypeNames =
                attr.stereotypes.map { it.lowercase() } +
                    attr.appliedStereotypes.map { it.stereotypeName.lowercase() }

            when {
                attrName.lowercase() == "id" || "id" in stereotypeNames -> {
                    hasIdAttribute = true
                    params +=
                        """
                        |    @Id
                        |    @GeneratedValue(strategy = GenerationType.IDENTITY)
                        |    val $attrName: $attrType = $attrDefault
                        """.trimMargin()
                }
                "transient" in stereotypeNames -> {
                    params +=
                        """
                        |    @Transient
                        |    val $attrName: $attrType = $attrDefault
                        """.trimMargin()
                }
                "embedded" in stereotypeNames -> {
                    params +=
                        """
                        |    @Embedded
                        |    val $attrName: $attrType = $attrDefault
                        """.trimMargin()
                }
                else -> {
                    params +=
                        """
                        |    @Column(name = "$colName", nullable = false)
                        |    val $attrName: $attrType = $attrDefault
                        """.trimMargin()
                }
            }
        }

        // Add association properties
        val assocParams = buildAssociationParams(cls, classById, classIdByName, associations)
        params.addAll(assocParams)

        // Synthetic @Id if none found
        if (!hasIdAttribute && cls.attributes.none { it.name.lowercase() == "id" }) {
            val syntheticId =
                """
                |    // Synthetic primary key — no «id» attribute found in the UML model.
                |    @Id
                |    @GeneratedValue(strategy = GenerationType.IDENTITY)
                |    val id: Long = 0L
                """.trimMargin()
            params.add(0, syntheticId)
        }

        if (params.isEmpty()) {
            sb.appendLine()
            sb.appendLine("    // Synthetic primary key — no attributes in the UML model.")
            sb.appendLine("    @Id")
            sb.appendLine("    @GeneratedValue(strategy = GenerationType.IDENTITY)")
            sb.append("    val id: Long = 0L,")
            sb.appendLine()
            sb.append(")")
        } else {
            sb.appendLine()
            sb.append(params.joinToString("\n\n") { "$it," })
            sb.appendLine()
            sb.append(")")
        }

        sb.appendLine()

        return EntityResult.Ok(GeneratedFile("${cls.name}.kt", sb.toString()))
    }

    private fun buildAssociationParams(
        cls: UmlClass,
        classById: Map<String, UmlClass>,
        classIdByName: Map<String, String>,
        associations: List<UmlAssociation>,
    ): List<String> {
        val params = mutableListOf<String>()

        for (assoc in associations) {
            if (assoc.ends.size != 2) continue
            val sourceEnd = assoc.ends[0]
            val targetEnd = assoc.ends[1]

            // This class is the source end
            val sourceId = sourceEnd.typeId
            val targetId = targetEnd.typeId
            val matchesSource =
                sourceId == cls.id ||
                    sourceId == cls.name ||
                    classIdByName[sourceId] == cls.id

            if (!matchesSource) continue

            val targetClass =
                classById[targetId] ?: classById[classIdByName[targetId] ?: ""] ?: continue
            val targetName = targetClass.name
            val propName = targetName.replaceFirstChar { it.lowercase() }

            // Determine multiplicity from the target end
            val upper = targetEnd.multiplicity.upper

            if (upper == null || upper > 1) {
                // one-to-many
                val collectionName = "${propName}s"
                val mappedByName = cls.name.replaceFirstChar { it.lowercase() }
                params +=
                    """
                    |    @OneToMany(mappedBy = "$mappedByName", cascade = [CascadeType.ALL], fetch = FetchType.LAZY)
                    |    val $collectionName: List<$targetName> = emptyList()
                    """.trimMargin()
            } else {
                // many-to-one (or one-to-one if lower == 1)
                val lower = targetEnd.multiplicity.lower
                if (lower == 1 && upper == 1) {
                    // Check if there's a reverse association to determine @OneToOne vs @ManyToOne
                    // Default: @ManyToOne
                    params +=
                        """
                        |    @ManyToOne(fetch = FetchType.LAZY)
                        |    @JoinColumn(name = "${toSnakeCase(propName)}_id")
                        |    val $propName: $targetName? = null
                        """.trimMargin()
                } else {
                    params +=
                        """
                        |    @ManyToOne(fetch = FetchType.LAZY)
                        |    @JoinColumn(name = "${toSnakeCase(propName)}_id")
                        |    val $propName: $targetName? = null
                        """.trimMargin()
                }
            }
        }

        return params
    }

    // ── Type mapping ──────────────────────────────────────────────────────────

    private fun jpaKotlinType(umlType: String): String =
        when (umlType.lowercase()) {
            "string", "str" -> "String"
            "integer", "int" -> "Long"
            "long" -> "Long"
            "boolean", "bool" -> "Boolean"
            "double", "float" -> "Double"
            else -> "String"
        }

    private fun jpaDefaultValue(umlType: String): String =
        when (umlType.lowercase()) {
            "string", "str" -> "\"\""
            "integer", "int", "long" -> "0L"
            "boolean", "bool" -> "false"
            "double", "float" -> "0.0"
            else -> "\"\""
        }

    // ── Name conversion ───────────────────────────────────────────────────────

    private fun toSnakeCase(name: String): String {
        val sb = StringBuilder()
        for ((i, ch) in name.withIndex()) {
            if (ch.isUpperCase() && i > 0) sb.append('_')
            sb.append(ch.lowercaseChar())
        }
        return sb.toString()
    }

    private fun String.toPlural(): String =
        when {
            endsWith("y") && length > 1 && this[length - 2].lowercaseChar() !in "aeiou" ->
                dropLast(1) + "ies"
            endsWith("s") ||
                endsWith("x") ||
                endsWith("z") ||
                endsWith("ch") ||
                endsWith("sh") -> "${this}es"
            else -> "${this}s"
        }

    private companion object {
        const val DEFAULT_PACKAGE = "com.example.entities"
        const val RULE_CLASS_TO_ENTITY = "uml-class-to-jpa-entity"
    }
}

/** ServiceLoader provider for [UmlToJpaTransformer]. */
public class UmlToJpaTransformerProvider : KumlTransformerProvider {
    override fun transformer(): UmlToJpaTransformer = UmlToJpaTransformer()
}
