plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.serialization) // for the vocabulary JSON contract test
}

kotlin {
    jvmToolchain(21)
    explicitApi()
}

dependencies {
    // Public surface: KumlCodeBlock is exposed on OkfDocument.kumlBlocks
    api(project(":kuml-docs:kuml-markdown"))
    // WorkspaceScaffolder.templateFiles(mode) exposes List<TemplateFile> on its public
    // signature — api (not implementation), or downstream modules (kuml-cli, kuml-desktop)
    // would fail with "cannot access class TemplateFile" under explicitApi().
    api(project(":kuml-scaffold")) // generic template-scaffold engine (V3.x, FT-Desktop-New-Workspace)
    implementation(libs.kotlinx.serialization.json)

    testImplementation(libs.kotest.runner.junit5)
    testImplementation(libs.kotest.assertions.core)
}

tasks.withType<Test>().configureEach {
    useJUnitPlatform()
    jvmArgs("-Xmx512m")
}

// ─────────────────────────────────────────────────────────────────────────────
// Modul-lokaler Spiegel von :kuml-cli's `generateVersionProperties` (siehe dort für die
// volle Begründung zu WriteProperties vs. ProcessResources' `expand`-Filter unter dem
// Configuration Cache). Reduziert auf den `version`-Key, weil `WorkspaceInitSpec.kumlVersion`
// nur diesen braucht (kein `gitSha`/`buildTime`). Da `version` projektweit über
// `allprojects` einheitlich gesetzt wird, liefert dies denselben String wie
// `dev.kuml.cli.KumlVersion.version` — byte-identischer Scaffold-Output in beiden Wegen
// (`kuml workspace init` CLI und kuml-desktop's "New Workspace…"-Dialog) ist damit
// strukturell garantiert.
// ─────────────────────────────────────────────────────────────────────────────
val generatedResourcesDirWorkspace = layout.buildDirectory.dir("generated/resources/version")

val generateWorkspaceVersionProperties =
    tasks.register<WriteProperties>("generateWorkspaceVersionProperties") {
        destinationFile.set(generatedResourcesDirWorkspace.map { it.file("dev/kuml/workspace/version.properties") })
        property("version", version.toString())
        comment =
            "Generated by :kuml-docs:kuml-workspace:generateWorkspaceVersionProperties — mirrors " +
            ":kuml-cli:generateVersionProperties so WorkspaceInitSpec.kumlVersion stays byte-identical to kuml --version."
    }

tasks.named<ProcessResources>("processResources") {
    exclude("dev/kuml/workspace/version.properties")
    from(generateWorkspaceVersionProperties.flatMap { it.destinationFile }) { into("dev/kuml/workspace") }
}
