package dev.kuml.codegen.m2m.docker

import dev.kuml.codegen.m2m.GeneratedFile
import dev.kuml.codegen.m2m.KumlTransformer
import dev.kuml.codegen.m2m.KumlTransformerProvider
import dev.kuml.codegen.m2m.TraceabilityLink
import dev.kuml.codegen.m2m.TransformContext
import dev.kuml.codegen.m2m.TransformResult
import dev.kuml.codegen.m2m.TransformTrace
import dev.kuml.core.model.KumlDiagram
import dev.kuml.uml.UmlComponent

/**
 * Transforms a UML component diagram into Dockerfiles (one per component).
 *
 * For each [UmlComponent] in the diagram:
 * - Emits one Dockerfile at `<ComponentName>/Dockerfile`
 * - The file is a JVM-ready Dockerfile using a slim Alpine JRE base image
 *
 * Name in COPY line uses kebab-case (e.g. `OrderService` → `order-service`).
 *
 * Options (via [TransformContext.options]):
 * - `"baseImage"` — FROM image, default `"eclipse-temurin:21-jre-alpine"`
 * - `"port"` — EXPOSE port, default `"8080"`
 * - `"buildDir"` — COPY source directory, default `"build/libs"`
 *
 * V2.x deferred: multi-stage builds, non-root user, health-check instructions,
 * ARG-based parameterization, build-arg for image tags.
 */
public class UmlToDockerTransformer : KumlTransformer<KumlDiagram, List<GeneratedFile>> {
    override val id: String = "uml-to-docker"
    override val description: String =
        "UML component diagram → Dockerfile per component"

    override fun transform(
        source: KumlDiagram,
        ctx: TransformContext,
    ): TransformResult<List<GeneratedFile>> {
        val baseImage = ctx.options["baseImage"] ?: DEFAULT_BASE_IMAGE
        val port = ctx.options["port"] ?: DEFAULT_PORT
        val buildDir = ctx.options["buildDir"] ?: DEFAULT_BUILD_DIR

        val components = source.elements.filterIsInstance<UmlComponent>()
        var trace = TransformTrace()
        val files = mutableListOf<GeneratedFile>()

        for (component in components) {
            val kebabName = camelCaseToKebab(component.name)
            val content =
                buildDockerfile(
                    componentName = component.name,
                    kebabName = kebabName,
                    baseImage = baseImage,
                    port = port,
                    buildDir = buildDir,
                )
            val relativePath = "${component.name}/Dockerfile"
            files += GeneratedFile(relativePath, content)
            trace = trace.plus(TraceabilityLink(component.id, relativePath, RULE_COMPONENT_TO_DOCKERFILE))
        }

        return TransformResult.Success(files, trace)
    }

    // ── Dockerfile generation ─────────────────────────────────────────────────

    private fun buildDockerfile(
        componentName: String,
        kebabName: String,
        baseImage: String,
        port: String,
        buildDir: String,
    ): String {
        val sb = StringBuilder()

        sb.appendLine("# Generated by kUML — kuml transform <script> --transformer uml-to-docker")
        sb.appendLine("# Component: $componentName")
        sb.appendLine()
        sb.appendLine("FROM $baseImage")
        sb.appendLine()
        sb.appendLine("WORKDIR /app")
        sb.appendLine()
        sb.appendLine("COPY $buildDir/$kebabName*.jar app.jar")
        sb.appendLine()
        sb.appendLine("EXPOSE $port")
        sb.appendLine()
        sb.append("""ENTRYPOINT ["java", "-jar", "app.jar"]""")

        return sb.toString().trimEnd() + "\n"
    }

    // ── Name conversion ───────────────────────────────────────────────────────

    /**
     * Converts a PascalCase or camelCase name to kebab-case.
     * Examples: `OrderService` → `order-service`, `paymentGateway` → `payment-gateway`
     */
    internal fun camelCaseToKebab(name: String): String =
        buildString {
            for ((i, ch) in name.withIndex()) {
                if (ch.isUpperCase() && i > 0) append('-')
                append(ch.lowercaseChar())
            }
        }

    private companion object {
        const val DEFAULT_BASE_IMAGE = "eclipse-temurin:21-jre-alpine"
        const val DEFAULT_PORT = "8080"
        const val DEFAULT_BUILD_DIR = "build/libs"
        const val RULE_COMPONENT_TO_DOCKERFILE = "uml-component-to-dockerfile"
    }
}

/** ServiceLoader provider for [UmlToDockerTransformer]. */
public class UmlToDockerTransformerProvider : KumlTransformerProvider {
    override fun transformer(): UmlToDockerTransformer = UmlToDockerTransformer()
}
