package dev.kuml.plugin.examples.typescript

import dev.kuml.codegen.api.KumlCodeGenerator
import dev.kuml.core.model.KumlDiagram
import dev.kuml.uml.UmlClass
import dev.kuml.uml.UmlEnumeration
import dev.kuml.uml.UmlInterface
import java.io.File

/**
 * Generates TypeScript interface/class/enum skeletons from UML class diagrams.
 *
 * One `.ts` file per top-level classifier (`UmlClass`, `UmlInterface`, `UmlEnumeration`).
 *
 * Type mapping (Kotlin/Java → TypeScript):
 *   String, UUID → string | Int, Long, Double, BigDecimal → number |
 *   Boolean → boolean | Date, LocalDate → Date | List, Collection → Array<unknown>
 */
public class TypeScriptCodeGenerator : KumlCodeGenerator {
    override val id: String = "typescript"
    override val displayName: String = "TypeScript"

    override fun generate(
        diagram: KumlDiagram,
        outputDir: File,
        options: Map<String, String>,
    ): List<File> {
        outputDir.mkdirs()
        val generated = mutableListOf<File>()
        for (element in diagram.elements) {
            when (element) {
                is UmlClass -> generated += generateClass(element, outputDir)
                is UmlInterface -> generated += generateInterface(element, outputDir)
                is UmlEnumeration -> generated += generateEnum(element, outputDir)
                else -> { /* skip non-classifier elements */ }
            }
        }
        return generated
    }

    private fun generateClass(
        cls: UmlClass,
        outputDir: File,
    ): File {
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML TypeScript Code Generator")
        sb.appendLine()
        val keyword = if (cls.isAbstract) "export abstract class " else "export class "
        sb.appendLine("${keyword}${cls.name} {")
        for (attr in cls.attributes) {
            val tsType = mapType(attr.type.name)
            val optional = if (attr.multiplicity.lower == 0) "?" else ""
            sb.appendLine("  ${attr.name}$optional: $tsType;")
        }
        if (cls.attributes.isNotEmpty() && cls.operations.isNotEmpty()) sb.appendLine()
        for (op in cls.operations) {
            val returnType = op.returnType?.let { mapType(it.name) } ?: "void"
            val params = op.parameters.joinToString(", ") { "${it.name}: ${mapType(it.type.name)}" }
            sb.appendLine("  ${op.name}($params): $returnType { throw new Error('Not implemented'); }")
        }
        sb.appendLine("}")
        val file = File(outputDir, "${cls.name}.ts")
        file.writeText(sb.toString())
        return file
    }

    private fun generateInterface(
        iface: UmlInterface,
        outputDir: File,
    ): File {
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML TypeScript Code Generator")
        sb.appendLine()
        sb.appendLine("export interface ${iface.name} {")
        for (attr in iface.attributes) {
            val tsType = mapType(attr.type.name)
            sb.appendLine("  ${attr.name}: $tsType;")
        }
        for (op in iface.operations) {
            val returnType = op.returnType?.let { mapType(it.name) } ?: "void"
            val params = op.parameters.joinToString(", ") { "${it.name}: ${mapType(it.type.name)}" }
            sb.appendLine("  ${op.name}($params): $returnType;")
        }
        sb.appendLine("}")
        val file = File(outputDir, "${iface.name}.ts")
        file.writeText(sb.toString())
        return file
    }

    private fun generateEnum(
        enum: UmlEnumeration,
        outputDir: File,
    ): File {
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML TypeScript Code Generator")
        sb.appendLine()
        sb.appendLine("export enum ${enum.name} {")
        enum.literals.forEachIndexed { i, lit ->
            val comma = if (i < enum.literals.size - 1) "," else ""
            sb.appendLine("  ${lit.name}$comma")
        }
        sb.appendLine("}")
        val file = File(outputDir, "${enum.name}.ts")
        file.writeText(sb.toString())
        return file
    }

    internal fun mapType(kumlType: String): String =
        when (kumlType.lowercase()) {
            "string", "uuid" -> "string"
            "int", "integer", "long", "short", "byte", "float", "double", "bigdecimal" -> "number"
            "boolean", "bool" -> "boolean"
            "void" -> "void"
            "date", "localdate", "localdatetime", "instant" -> "Date"
            "list", "collection", "iterable", "set" -> "Array<unknown>"
            "map" -> "Record<string, unknown>"
            else -> kumlType
        }
}
