package dev.kuml.transform.bpmnuml

import dev.kuml.bpmn.model.BpmnEvent
import dev.kuml.bpmn.model.BpmnGateway
import dev.kuml.bpmn.model.BpmnProcess
import dev.kuml.bpmn.model.BpmnTask
import dev.kuml.bpmn.model.EventPosition
import dev.kuml.bpmn.model.GatewayType

/**
 * Renders a [BpmnProcess] to a kUML BPMN model script string.
 *
 * The emitted script uses the `bpmnModel { process { … } }` DSL.
 */
internal object BpmnProcessScriptRenderer {
    fun render(process: BpmnProcess): String {
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML UML Activity→BPMN transformer — do not edit manually.")
        sb.appendLine("// Source diagram: ${process.name ?: process.id}")
        sb.appendLine()
        sb.appendLine("bpmnModel(\"${escapeString(process.name ?: process.id)}\") {")
        val processId = escapeString(process.id)
        val processName = escapeString(process.name ?: process.id)
        sb.appendLine("""    process(id = "$processId", name = "$processName") {""")
        sb.appendLine()

        // id → stable val name
        val idToVal = mutableMapOf<String, String>()
        val usedNames = mutableSetOf<String>()
        for (node in process.flowNodes) {
            var candidate = toKotlinIdent(node.id)
            if (candidate in usedNames) {
                var suffix = 2
                while ("${candidate}_$suffix" in usedNames) suffix++
                candidate = "${candidate}_$suffix"
            }
            idToVal[node.id] = candidate
            usedNames += candidate
        }

        // Declare nodes
        for (node in process.flowNodes) {
            val valName = idToVal[node.id] ?: continue
            when (node) {
                is BpmnTask -> {
                    val name = node.name?.let { """ "${escapeString(it)}"""" } ?: ""
                    sb.appendLine("""        val $valName = task(name =$name)""")
                }
                is BpmnEvent -> {
                    when (node.position) {
                        EventPosition.START -> {
                            val name = node.name?.let { """ "${escapeString(it)}"""" } ?: ""
                            sb.appendLine("""        val $valName = startEvent(name =$name)""")
                        }
                        EventPosition.END -> {
                            val name = node.name?.let { """ "${escapeString(it)}"""" } ?: ""
                            sb.appendLine("""        val $valName = endEvent(name =$name)""")
                        }
                        EventPosition.INTERMEDIATE -> {
                            val name = node.name?.let { """ "${escapeString(it)}"""" } ?: ""
                            sb.appendLine("""        val $valName = intermediateEvent(name =$name)""")
                        }
                    }
                }
                is BpmnGateway -> {
                    val gwFn =
                        when (node.gatewayType) {
                            GatewayType.PARALLEL -> "gateway(type = GatewayType.PARALLEL)"
                            GatewayType.INCLUSIVE -> "gateway(type = GatewayType.INCLUSIVE)"
                            GatewayType.EVENT_BASED -> "gateway(type = GatewayType.EVENT_BASED)"
                            GatewayType.COMPLEX -> "gateway(type = GatewayType.COMPLEX)"
                            else -> "gateway(type = GatewayType.EXCLUSIVE)"
                        }
                    sb.appendLine("        val $valName = $gwFn")
                }
                else -> {
                    // BpmnSubProcess, BpmnCallActivity — best-effort as task
                    val name = node.name?.let { """ "${escapeString(it)}"""" } ?: ""
                    sb.appendLine("""        val $valName = task(name =$name)""")
                }
            }
        }

        if (process.sequenceFlows.isNotEmpty()) sb.appendLine()

        // Emit sequence flows
        for (flow in process.sequenceFlows) {
            val fromVal = idToVal[flow.sourceRef] ?: continue
            val toVal = idToVal[flow.targetRef] ?: continue
            val cond = flow.conditionExpression
            if (cond != null) {
                sb.appendLine("""        sequenceFlow(from = $fromVal, to = $toVal, condition = "${escapeString(cond)}")""")
            } else {
                sb.appendLine("        sequenceFlow(from = $fromVal, to = $toVal)")
            }
        }

        sb.appendLine("    }")
        sb.appendLine()
        sb.appendLine("""    diagram("$processName", processId = "$processId")""")
        sb.appendLine("}")
        sb.appendLine()

        return sb.toString()
    }

    private fun toKotlinIdent(id: String): String {
        val cleaned = id.replace(Regex("[^a-zA-Z0-9_]"), "_")
        return if (cleaned.isEmpty() || cleaned[0].isDigit()) "node_$cleaned" else cleaned
    }

    private fun escapeString(s: String): String =
        s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
}
