package dev.kuml.transform.bpmnuml

import dev.kuml.uml.UmlActivityNodeKind

/**
 * Renders a [UmlActivityModel] to a kUML activity-diagram script string.
 *
 * The emitted script uses the `activityDiagram(name = "…") { … }` DSL.
 * Each [dev.kuml.uml.UmlActivityNode] maps to the corresponding builder function:
 * [UmlActivityNodeKind.ACTION] → `action(name = "…")`,
 * [UmlActivityNodeKind.INITIAL] → `initialNode()`,
 * [UmlActivityNodeKind.ACTIVITY_FINAL] → `finalNode()`,
 * [UmlActivityNodeKind.FLOW_FINAL] → `flowFinal()`,
 * [UmlActivityNodeKind.DECISION] → `decision()`,
 * [UmlActivityNodeKind.MERGE] → `merge()`,
 * [UmlActivityNodeKind.FORK] → `fork()`,
 * [UmlActivityNodeKind.JOIN] → `join()`,
 * [UmlActivityNodeKind.OBJECT] → `objectNode(name = "…")`.
 *
 * Lane membership (if recorded in node metadata under `"uml.partition"`) is
 * emitted as a Kotlin comment — the kUML UML Activity metamodel has no
 * PARTITION node kind.
 */
internal object UmlActivityScriptRenderer {
    fun render(model: UmlActivityModel): String {
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML BPMN→UML Activity transformer — do not edit manually.")
        sb.appendLine("// Source process: ${model.name}")
        sb.appendLine()
        sb.appendLine("""activityDiagram(name = "${escapeString(model.name)}") {""")
        sb.appendLine()

        // Build a map from node id → stable Kotlin val name
        val idToVal = mutableMapOf<String, String>()
        val usedNames = mutableSetOf<String>()
        for (node in model.nodes) {
            var candidate = toKotlinIdent(node.id)
            if (candidate in usedNames) {
                var suffix = 2
                while ("${candidate}_$suffix" in usedNames) suffix++
                candidate = "${candidate}_$suffix"
            }
            idToVal[node.id] = candidate
            usedNames += candidate
        }

        // Emit node declarations
        for (node in model.nodes) {
            val valName = idToVal[node.id] ?: continue
            val partitionComment = (node.metadata["uml.partition"] as? dev.kuml.core.model.KumlMetaValue.Text)?.value
            if (partitionComment != null) {
                sb.appendLine("    // partition: $partitionComment")
            }
            val inclusiveComment = (node.metadata["bpmn.gatewayType"] as? dev.kuml.core.model.KumlMetaValue.Text)?.value
            if (inclusiveComment != null) {
                sb.appendLine("    // gateway type: $inclusiveComment (best-effort; UML has no inclusive decision)")
            }
            val decl =
                when (node.kind) {
                    UmlActivityNodeKind.INITIAL -> "val $valName = initialNode()"
                    UmlActivityNodeKind.ACTIVITY_FINAL -> "val $valName = finalNode()"
                    UmlActivityNodeKind.FLOW_FINAL -> "val $valName = flowFinal()"
                    UmlActivityNodeKind.DECISION -> "val $valName = decision()"
                    UmlActivityNodeKind.MERGE -> "val $valName = merge()"
                    UmlActivityNodeKind.FORK -> "val $valName = fork()"
                    UmlActivityNodeKind.JOIN -> "val $valName = join()"
                    UmlActivityNodeKind.ACTION -> """val $valName = action(name = "${escapeString(node.name)}")"""
                    UmlActivityNodeKind.OBJECT -> """val $valName = objectNode(name = "${escapeString(node.name)}")"""
                }
            sb.appendLine("    $decl")
        }

        if (model.edges.isNotEmpty()) sb.appendLine()

        // Emit edges
        for (edge in model.edges) {
            val fromVal = idToVal[edge.sourceId] ?: continue
            val toVal = idToVal[edge.targetId] ?: continue
            val guardPart = edge.guard?.let { g -> """, guard = "${escapeString(g)}"""" } ?: ""
            sb.appendLine("    edge(from = $fromVal, to = $toVal$guardPart)")
        }

        sb.appendLine()
        sb.append("}")
        sb.appendLine()

        return sb.toString()
    }

    /** Converts a BPMN element id to a valid Kotlin identifier (camelCase, no spaces). */
    private fun toKotlinIdent(id: String): String {
        val cleaned = id.replace(Regex("[^a-zA-Z0-9_]"), "_")
        return if (cleaned.isEmpty() || cleaned[0].isDigit()) "node_$cleaned" else cleaned
    }

    /** Escapes a string for embedding in a Kotlin string literal. */
    private fun escapeString(s: String): String =
        s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
}
