package dev.kuml.cli.reverse

import dev.kuml.core.model.KumlMetaValue
import dev.kuml.core.model.KumlModel
import dev.kuml.uml.UmlComponent
import dev.kuml.uml.UmlInterface
import dev.kuml.uml.UmlNamedElement
import dev.kuml.uml.UmlOperation
import dev.kuml.uml.UmlPackage
import dev.kuml.uml.UmlPort

/**
 * Prints a [KumlModel] whose `root` is a [UmlPackage] (as produced by ARXML import) as a
 * `*.kuml.kts` source string using the AUTOSAR profile stereotypes.
 *
 * This printer is specifically designed for models produced by [ArxmlModelMerge.merge] —
 * i.e. models whose root is a nested [UmlPackage] hierarchy with AUTOSAR stereotypes
 * ([dev.kuml.io.arxml.ArxmlSchema.STEREOTYPE_SOFTWARE_COMPONENT], etc.).
 *
 * The output uses the raw UML metamodel constructors (not the kUML DSL builders) because
 * the AUTOSAR model structure does not map cleanly to `componentDiagram { ... }` — it has
 * nested `UmlPackage` wrappers, `interfaceRef` metadata for TREFs, runnable triggers etc.
 *
 * Format:
 * ```kotlin
 * // AUTOSAR model: <name>
 * // Generated by kuml reverse --format arxml
 * dev.kuml.core.model.KumlModel(
 *     root = dev.kuml.uml.UmlPackage(
 *         id = "...",
 *         name = "AUTOSAR",
 *         members = listOf(
 *             dev.kuml.uml.UmlPackage(name = "Interfaces", ...),
 *             dev.kuml.uml.UmlPackage(name = "Components", ...),
 *         )
 *     ),
 *     language = dev.kuml.core.model.ModelingLanguage.UML,
 *     level = dev.kuml.core.model.ModelLevel.PIM,
 *     name = "<name>",
 * )
 * ```
 *
 * V3.1.36 — initial implementation.
 */
internal object ArxmlPackageDslPrinter {
    internal fun print(model: KumlModel): String {
        val root = model.root
        if (root !is UmlPackage) {
            return "// model root is not a UmlPackage — cannot serialize as AUTOSAR DSL\n"
        }
        val sb = StringBuilder()
        sb.appendLine("// AUTOSAR model: ${model.name}")
        sb.appendLine("// Generated by kuml reverse --format arxml")
        sb.appendLine("@file:Suppress(\"unused\")")
        sb.appendLine()
        sb.appendLine("import dev.kuml.core.model.KumlMetaValue")
        sb.appendLine("import dev.kuml.core.model.KumlModel")
        sb.appendLine("import dev.kuml.core.model.ModelLevel")
        sb.appendLine("import dev.kuml.core.model.ModelingLanguage")
        sb.appendLine("import dev.kuml.uml.UmlComponent")
        sb.appendLine("import dev.kuml.uml.UmlInterface")
        sb.appendLine("import dev.kuml.uml.UmlOperation")
        sb.appendLine("import dev.kuml.uml.UmlPackage")
        sb.appendLine("import dev.kuml.uml.UmlPort")
        sb.appendLine()
        sb.appendLine("KumlModel(")
        sb.appendLine("    root = ${printPackage(root, "    ")},")
        sb.appendLine("    language = ModelingLanguage.UML,")
        sb.appendLine("    level = ModelLevel.PIM,")
        sb.appendLine("    name = ${quote(model.name)},")
        sb.appendLine(")")
        return sb.toString()
    }

    private fun printPackage(
        pkg: UmlPackage,
        indent: String,
    ): String {
        val inner = "$indent    "
        val sb = StringBuilder()
        sb.append("UmlPackage(\n")
        sb.append("$inner    id = ${quote(pkg.id)},\n")
        sb.append("$inner    name = ${quote(pkg.name)},\n")
        if (pkg.members.isEmpty()) {
            sb.append("$inner    members = emptyList(),\n")
        } else {
            sb.append("$inner    members = listOf(\n")
            for (member in pkg.members) {
                sb.append("$inner        ${printMember(member, "$inner        ")},\n")
            }
            sb.append("$inner    ),\n")
        }
        sb.append("$inner)")
        return sb.toString()
    }

    private fun printMember(
        member: UmlNamedElement,
        indent: String,
    ): String =
        when (member) {
            is UmlPackage -> printPackage(member, indent)
            is UmlComponent -> printComponent(member, indent)
            is UmlInterface -> printInterface(member, indent)
            else -> "// unsupported element type: ${member::class.simpleName}"
        }

    private fun printComponent(
        comp: UmlComponent,
        indent: String,
    ): String {
        val inner = "$indent    "
        val sb = StringBuilder()
        sb.append("UmlComponent(\n")
        sb.append("$inner    id = ${quote(comp.id)},\n")
        sb.append("$inner    name = ${quote(comp.name)},\n")
        if (comp.stereotypes.isNotEmpty()) {
            sb.append("$inner    stereotypes = listOf(${comp.stereotypes.joinToString { quote(it) }}),\n")
        }
        if (comp.metadata.isNotEmpty()) {
            sb.append("$inner    metadata = mapOf(${printMetadata(comp.metadata)}),\n")
        }
        if (comp.ports.isNotEmpty()) {
            sb.append("$inner    ports = listOf(\n")
            for (port in comp.ports) {
                sb.append("$inner        ${printPort(port, "$inner        ")},\n")
            }
            sb.append("$inner    ),\n")
        }
        if (comp.operations.isNotEmpty()) {
            sb.append("$inner    operations = listOf(\n")
            for (op in comp.operations) {
                sb.append("$inner        ${printOperation(op, "$inner        ")},\n")
            }
            sb.append("$inner    ),\n")
        }
        sb.append("$inner)")
        return sb.toString()
    }

    private fun printInterface(
        iface: UmlInterface,
        indent: String,
    ): String {
        val inner = "$indent    "
        val sb = StringBuilder()
        sb.append("UmlInterface(\n")
        sb.append("$inner    id = ${quote(iface.id)},\n")
        sb.append("$inner    name = ${quote(iface.name)},\n")
        if (iface.stereotypes.isNotEmpty()) {
            sb.append("$inner    stereotypes = listOf(${iface.stereotypes.joinToString { quote(it) }}),\n")
        }
        if (iface.metadata.isNotEmpty()) {
            sb.append("$inner    metadata = mapOf(${printMetadata(iface.metadata)}),\n")
        }
        sb.append("$inner)")
        return sb.toString()
    }

    private fun printPort(
        port: UmlPort,
        indent: String,
    ): String {
        val inner = "$indent    "
        val sb = StringBuilder()
        sb.append("UmlPort(\n")
        sb.append("$inner    id = ${quote(port.id)},\n")
        sb.append("$inner    name = ${quote(port.name)},\n")
        if (port.stereotypes.isNotEmpty()) {
            sb.append("$inner    stereotypes = listOf(${port.stereotypes.joinToString { quote(it) }}),\n")
        }
        if (port.metadata.isNotEmpty()) {
            sb.append("$inner    metadata = mapOf(${printMetadata(port.metadata)}),\n")
        }
        sb.append("$inner)")
        return sb.toString()
    }

    private fun printOperation(
        op: UmlOperation,
        indent: String,
    ): String {
        val inner = "$indent    "
        val sb = StringBuilder()
        sb.append("UmlOperation(\n")
        sb.append("$inner    id = ${quote(op.id)},\n")
        sb.append("$inner    name = ${quote(op.name)},\n")
        if (op.stereotypes.isNotEmpty()) {
            sb.append("$inner    stereotypes = listOf(${op.stereotypes.joinToString { quote(it) }}),\n")
        }
        if (op.metadata.isNotEmpty()) {
            sb.append("$inner    metadata = mapOf(${printMetadata(op.metadata)}),\n")
        }
        sb.append("$inner)")
        return sb.toString()
    }

    private fun printMetadata(metadata: Map<String, KumlMetaValue>): String =
        metadata.entries.joinToString(", ") { (k, v) ->
            when (v) {
                is KumlMetaValue.Text -> "${quote(k)} to KumlMetaValue.Text(${quote(v.value)})"
                is KumlMetaValue.Integer -> "${quote(k)} to KumlMetaValue.Integer(${v.value}L)"
                is KumlMetaValue.Decimal -> "${quote(k)} to KumlMetaValue.Decimal(${v.value})"
                is KumlMetaValue.Flag -> "${quote(k)} to KumlMetaValue.Flag(${v.value})"
                else -> "${quote(k)} to KumlMetaValue.Text(${quote(v.toString())})"
            }
        }

    private fun quote(s: String): String = "\"" + s.replace("\\", "\\\\").replace("\"", "\\\"") + "\""
}
