package dev.kuml.cli.reverse

import dev.kuml.erm.model.ErmAttribute
import dev.kuml.erm.model.ErmCategory
import dev.kuml.erm.model.ErmDataType
import dev.kuml.erm.model.ErmEntity
import dev.kuml.erm.model.ErmIndex
import dev.kuml.erm.model.ErmModel
import dev.kuml.erm.model.ErmNotation
import dev.kuml.erm.model.ErmRelationship
import dev.kuml.erm.model.ErmView
import dev.kuml.erm.model.ReferentialAction
import dev.kuml.erm.model.RelationshipKind

/**
 * Pretty-prints an [ErmModel] as an `ermModel(name = "…") { … }` `*.kuml.kts`
 * source string (V3.4.9 — `kuml reverse --format sql`).
 *
 * Deliberately mirrors `dev.kuml.transform.umlerm.ErmScriptRenderer`
 * (`kuml-transform-uml-to-erm`, V3.4.6) — same topological entity ordering,
 * `val` binding scheme, and DSL surface — so a model reversed from SQL and a
 * model transformed from UML render to structurally identical-looking DSL.
 * `ErmScriptRenderer` is `internal` to its own module and that module is not a
 * `kuml-cli` dependency, so this is a deliberate, small duplication rather
 * than a shared dependency; unlike `ErmScriptRenderer`, this printer also
 * renders [ErmEntity.indexes] and [ErmModel.views] — first-class elements a
 * SQL reverse produces routinely (`CREATE INDEX`, `CREATE VIEW`) that the
 * UML→ERM transform never emits. A follow-up consolidation (extracting a
 * shared `ErmDslWriter` into `kuml-metamodel-erm` commonMain) is tracked as a
 * separate ticket, not part of V3.4.9.
 */
internal object ErmModelDslPrinter {
    fun print(model: ErmModel): String {
        val order = topoSortEntities(model)
        val valNames = allocateValNames(order)

        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML SQL→ERM reverse engine — do not edit manually.")
        sb.appendLine("// Source model: ${sanitizeComment(model.name)}")
        sb.appendLine()
        sb.appendLine("""ermModel(name = "${escape(model.name)}") {""")
        sb.appendLine()

        for (entity in order) {
            renderEntity(sb, entity, valNames)
        }

        if (model.relationships.isNotEmpty()) sb.appendLine()
        for (rel in model.relationships) {
            renderRelationship(sb, rel, valNames)
        }

        if (model.views.isNotEmpty()) sb.appendLine()
        for (view in model.views) {
            renderView(sb, view, valNames)
        }

        if (model.categories.isNotEmpty()) sb.appendLine()
        for (category in model.categories) {
            renderCategory(sb, category, valNames)
        }

        val notation = model.diagrams.firstOrNull()?.notation ?: ErmNotation.MARTIN
        val showIndexes = model.diagrams.firstOrNull()?.showIndexes ?: false
        sb.appendLine()
        val diagramArgs = mutableListOf("""name = "${escape(model.name)}"""", "notation = ErmNotation.$notation")
        if (showIndexes) diagramArgs += "showIndexes = true"
        sb.appendLine("""    diagram(${diagramArgs.joinToString(", ")})""")
        sb.append("}")
        sb.appendLine()
        return sb.toString()
    }

    // ── Entities ──────────────────────────────────────────────────────────────

    private fun renderEntity(
        sb: StringBuilder,
        entity: ErmEntity,
        valNames: Map<String, String>,
    ) {
        val valName = valNames.getValue(entity.id)
        val weakPart = if (entity.weak) ", weak = true" else ""
        sb.appendLine("""    val $valName = entity("${escape(entity.name ?: entity.id)}"$weakPart) {""")
        for (attr in entity.attributes) {
            renderAttribute(sb, attr, valNames)
        }
        for (index in entity.indexes) {
            renderIndex(sb, index, entity)
        }
        for (check in entity.checks) {
            val namePart = check.name?.let { """, name = "${escape(it)}"""" } ?: ""
            sb.appendLine("""        check("${escape(check.expression)}"$namePart)""")
        }
        sb.appendLine("    }")
        sb.appendLine()
    }

    private fun renderAttribute(
        sb: StringBuilder,
        attr: ErmAttribute,
        valNames: Map<String, String>,
    ) {
        val parts = mutableListOf<String>()
        parts += "\"${escape(attr.name ?: "")}\""
        parts += renderType(attr.type)
        if (attr.primaryKey) parts += "primaryKey = true"
        if (!attr.nullable) parts += "nullable = false"
        if (attr.unique) parts += "unique = true"
        attr.default?.let { parts += "default = \"${escape(it)}\"" }
        if (attr.autoIncrement) parts += "autoIncrement = true"
        attr.foreignKey?.let { fk ->
            val targetVal = valNames[fk.targetEntityId] ?: "\"${escape(fk.targetEntityId)}\""
            val fkParts = mutableListOf("targetEntityId = $targetVal")
            if (fk.onDelete != ReferentialAction.NO_ACTION) fkParts += "onDelete = ReferentialAction.${fk.onDelete}"
            if (fk.onUpdate != ReferentialAction.NO_ACTION) fkParts += "onUpdate = ReferentialAction.${fk.onUpdate}"
            parts += "foreignKey = ErmForeignKey(${fkParts.joinToString(", ")})"
        }
        sb.appendLine("        attribute(${parts.joinToString(", ")})")
    }

    private fun renderIndex(
        sb: StringBuilder,
        index: ErmIndex,
        entity: ErmEntity,
    ) {
        val attrNames = index.attributeIds.mapNotNull { id -> entity.attributes.firstOrNull { it.id == id }?.name }
        if (attrNames.size != index.attributeIds.size) return // dangling attribute id — skip rather than emit a broken call
        val parts = attrNames.map { "\"${escape(it)}\"" }.toMutableList()
        if (index.unique) parts += "unique = true"
        index.name?.let { parts += "name = \"${escape(it)}\"" }
        sb.appendLine("        index(${parts.joinToString(", ")})")
    }

    private fun renderType(type: ErmDataType): String =
        when (type) {
            is ErmDataType.Integer -> "ErmDataType.Integer(${type.bits})"
            is ErmDataType.Decimal -> "ErmDataType.Decimal(${type.precision}, ${type.scale})"
            is ErmDataType.Real -> "ErmDataType.Real(double = ${type.double})"
            is ErmDataType.Varchar -> "ErmDataType.Varchar(${type.length})"
            ErmDataType.Text -> "ErmDataType.Text"
            ErmDataType.Boolean -> "ErmDataType.Boolean"
            ErmDataType.Date -> "ErmDataType.Date"
            ErmDataType.Time -> "ErmDataType.Time"
            is ErmDataType.Timestamp -> "ErmDataType.Timestamp(withTimeZone = ${type.withTimeZone})"
            ErmDataType.Uuid -> "ErmDataType.Uuid"
            ErmDataType.Blob -> "ErmDataType.Blob"
            ErmDataType.Json -> "ErmDataType.Json"
            is ErmDataType.Custom -> "ErmDataType.Custom(\"${escape(type.raw)}\")"
        }

    // ── Relationships / Views / Categories ─────────────────────────────────────

    private fun renderRelationship(
        sb: StringBuilder,
        rel: ErmRelationship,
        valNames: Map<String, String>,
    ) {
        val from = valNames[rel.sourceEntityId] ?: return
        val to = valNames[rel.targetEntityId] ?: return
        val parts = mutableListOf("from = $from", "to = $to")
        rel.name?.let { parts += "name = \"${escape(it)}\"" }
        parts += "sourceCardinality = Cardinality(min = ${rel.sourceCardinality.min}, max = ${rel.sourceCardinality.max})"
        parts += "targetCardinality = Cardinality(min = ${rel.targetCardinality.min}, max = ${rel.targetCardinality.max})"
        if (rel.kind != RelationshipKind.NON_IDENTIFYING) parts += "kind = RelationshipKind.${rel.kind}"
        rel.sourceRole?.let { parts += "sourceRole = \"${escape(it)}\"" }
        rel.targetRole?.let { parts += "targetRole = \"${escape(it)}\"" }
        sb.appendLine("    relationship(${parts.joinToString(", ")})")
    }

    private fun renderView(
        sb: StringBuilder,
        view: ErmView,
        valNames: Map<String, String>,
    ) {
        val parts = mutableListOf("""name = "${escape(view.name ?: "")}"""", """query = "${escape(view.query)}"""")
        val refs = view.referencedEntityIds.mapNotNull { valNames[it] }
        if (refs.isNotEmpty()) parts += "references = listOf(${refs.joinToString(", ")})"
        sb.appendLine("    view(${parts.joinToString(", ")})")
    }

    private fun renderCategory(
        sb: StringBuilder,
        category: ErmCategory,
        valNames: Map<String, String>,
    ) {
        val supertype = valNames[category.supertypeEntityId] ?: return
        val subtypes = category.subtypeEntityIds.mapNotNull { valNames[it] }
        if (subtypes.isEmpty()) return
        val parts = mutableListOf("supertype = $supertype", "subtypes = listOf(${subtypes.joinToString(", ")})")
        category.name?.let { parts += "name = \"${escape(it)}\"" }
        if (category.complete) parts += "complete = true"
        sb.appendLine("    category(${parts.joinToString(", ")})")
    }

    // ── Ordering / naming helpers ─────────────────────────────────────────────

    /** Kahn/DFS-style topological sort by FK dependency; falls back to declaration order on cycles. */
    private fun topoSortEntities(model: ErmModel): List<ErmEntity> {
        val byId = model.entities.associateBy { it.id }
        val deps: Map<String, Set<String>> =
            model.entities.associate { entity ->
                entity.id to
                    entity.attributes
                        .mapNotNull { it.foreignKey?.targetEntityId }
                        .filter { it != entity.id && it in byId }
                        .toSet()
            }
        val visited = mutableSetOf<String>()
        val inProgress = mutableSetOf<String>()
        val result = mutableListOf<ErmEntity>()

        fun visit(entityId: String) {
            if (entityId in visited || entityId in inProgress) return
            inProgress += entityId
            deps[entityId].orEmpty().forEach(::visit)
            inProgress -= entityId
            visited += entityId
            byId[entityId]?.let { result += it }
        }

        for (entity in model.entities) visit(entity.id)
        return result
    }

    private fun allocateValNames(entities: List<ErmEntity>): Map<String, String> {
        val used = mutableSetOf<String>()
        val map = mutableMapOf<String, String>()
        for (entity in entities) {
            val base = toKotlinIdent(entity.name ?: entity.id)
            var candidate = base
            var suffix = 2
            while (candidate in used) {
                candidate = "${base}_$suffix"
                suffix++
            }
            used += candidate
            map[entity.id] = candidate
        }
        return map
    }

    private fun toKotlinIdent(raw: String): String {
        val cleaned = raw.replace(Regex("[^a-zA-Z0-9_]"), "_")
        return if (cleaned.isEmpty() || cleaned[0].isDigit()) "e_$cleaned" else cleaned
    }

    private fun escape(s: String): String =
        s
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("$", "\${'$'}")

    /**
     * Neutralizes CR/LF in text emitted inside a single-line `//` Kotlin comment.
     *
     * Mirrors `ErmScriptRenderer.sanitizeComment` — see that KDoc for the injection
     * rationale (a raw newline here would terminate the comment early and let the
     * remainder of user-controlled text execute as top-level Kotlin).
     */
    private fun sanitizeComment(s: String): String = s.replace("\r\n", " ").replace('\n', ' ').replace('\r', ' ')
}
