package dev.kuml.codegen.java

import dev.kuml.codegen.api.KumlCodeGenerator
import dev.kuml.core.model.KumlDiagram
import dev.kuml.uml.UmlClass
import dev.kuml.uml.UmlEnumeration
import dev.kuml.uml.UmlInterface
import dev.kuml.uml.UmlOperation
import dev.kuml.uml.UmlProperty
import dev.kuml.uml.Visibility
import java.io.File

/**
 * V1.1.4 — Java POJO Code Generator.
 *
 * Optionen via `options`-Map:
 *  - `package`    — Java-Paket (z.B. `com.example.domain`). Default: kein Paket (flach).
 *  - `java-style` — `pojo` (default) / `records` / `lombok`.
 *
 * Schreibt für jede `UmlClass`/`UmlInterface`/`UmlEnumeration` eine `.java`-
 * Datei in eine echte Paket-Verzeichnisstruktur (`outputDir/com/example/User.java`).
 *
 * Stereotyp-aware: JavaEE-Stereotypen werden als JPA-Annotations ausgegeben.
 * `«Transient»`/`«Internal»` schließen Properties aus.
 */
public class JavaCodeGenerator : KumlCodeGenerator {
    override val id: String = "java"
    override val displayName: String = "Java (POJOs, Records, or Lombok)"

    override fun generate(
        diagram: KumlDiagram,
        outputDir: File,
        options: Map<String, String>,
    ): List<File> {
        val pkg = options["package"]?.takeIf { it.isNotBlank() }
        val style = JavaStyle.from(options["java-style"] ?: "pojo")

        val packageDir =
            if (pkg != null) File(outputDir, pkg.replace('.', File.separatorChar)) else outputDir
        packageDir.mkdirs()

        val written = mutableListOf<File>()
        for (element in diagram.elements) {
            val file: File? =
                when (element) {
                    is UmlClass -> renderClass(element, packageDir, pkg, style)
                    is UmlInterface -> renderInterface(element, packageDir, pkg)
                    is UmlEnumeration -> renderEnum(element, packageDir, pkg)
                    else -> null
                }
            if (file != null) written += file
        }
        return written
    }

    // ── Class ────────────────────────────────────────────────────────────────

    private fun renderClass(
        cls: UmlClass,
        packageDir: File,
        pkg: String?,
        style: JavaStyle,
    ): File {
        val visibleAttrs =
            cls.attributes.filterNot { JavaStereotypeMapper.isExcluded(it.appliedStereotypes) }
        val file = File(packageDir, "${cls.name}.java")
        val sb = StringBuilder()

        sb.appendLine("// Generated by kUML — do not edit by hand.")
        if (pkg != null) sb.appendLine("package $pkg;").appendLine()

        // Class-level annotations from stereotypes
        for (stereo in cls.appliedStereotypes) {
            JavaStereotypeMapper.toAnnotation(stereo)?.let { sb.appendLine(it) }
        }
        if (style == JavaStyle.LOMBOK) {
            sb.appendLine("@lombok.Data")
            sb.appendLine("@lombok.NoArgsConstructor")
            sb.appendLine("@lombok.AllArgsConstructor")
        }

        // Class declaration — records get a different head
        val abstractMod = if (cls.isAbstract) "abstract " else ""
        if (style == JavaStyle.RECORDS) {
            // Records can't be abstract; if isAbstract, fall back to POJO style declaration
            // (we keep behavior simple and still emit a record — abstract is rare for value types).
            val params =
                visibleAttrs.joinToString(", ") {
                    "${JavaTypeMapper.toJavaType(it.type, it.multiplicity)} ${it.name}"
                }
            sb.appendLine("public record ${cls.name}($params) {}")
        } else {
            sb.append("public ${abstractMod}class ${cls.name}")
            sb.appendLine(" {").appendLine()
            when (style) {
                JavaStyle.POJO -> renderPojoBody(sb, cls, visibleAttrs)
                JavaStyle.LOMBOK -> renderLombokBody(sb, visibleAttrs)
                JavaStyle.RECORDS -> Unit // already emitted above
            }
            // Operations as TODO method stubs
            renderOperations(sb, cls.operations)
            sb.appendLine("}")
        }

        file.writeText(sb.toString())
        return file
    }

    private fun renderPojoBody(
        sb: StringBuilder,
        cls: UmlClass,
        attrs: List<UmlProperty>,
    ) {
        // Fields
        for (attr in attrs) {
            for (stereo in attr.appliedStereotypes) {
                JavaStereotypeMapper.toAnnotation(stereo)?.let { sb.appendLine("    $it") }
            }
            val type = JavaTypeMapper.toJavaType(attr.type, attr.multiplicity)
            sb.appendLine("    private $type ${attr.name};")
        }
        sb.appendLine()

        // No-args constructor
        sb.appendLine("    public ${cls.name}() {}").appendLine()

        // All-args constructor
        if (attrs.isNotEmpty()) {
            val params =
                attrs.joinToString(", ") {
                    "${JavaTypeMapper.toJavaType(it.type, it.multiplicity)} ${it.name}"
                }
            sb.appendLine("    public ${cls.name}($params) {")
            for (a in attrs) sb.appendLine("        this.${a.name} = ${a.name};")
            sb.appendLine("    }").appendLine()
        }

        // Getters / Setters
        for (attr in attrs) {
            val type = JavaTypeMapper.toJavaType(attr.type, attr.multiplicity)
            val cap = attr.name.replaceFirstChar { it.uppercaseChar() }
            sb.appendLine("    public $type get$cap() { return ${attr.name}; }")
            sb.appendLine("    public void set$cap($type ${attr.name}) { this.${attr.name} = ${attr.name}; }")
            sb.appendLine()
        }
    }

    private fun renderLombokBody(
        sb: StringBuilder,
        attrs: List<UmlProperty>,
    ) {
        sb.appendLine("    // @lombok.Data generates getters, setters, equals, hashCode, toString")
        for (attr in attrs) {
            for (stereo in attr.appliedStereotypes) {
                JavaStereotypeMapper.toAnnotation(stereo)?.let { sb.appendLine("    $it") }
            }
            val type = JavaTypeMapper.toJavaType(attr.type, attr.multiplicity)
            sb.appendLine("    private $type ${attr.name};")
        }
        sb.appendLine()
    }

    private fun renderOperations(
        sb: StringBuilder,
        operations: List<UmlOperation>,
    ) {
        for (op in operations) {
            val visibility = op.visibility.toJavaModifier()
            val returnType =
                if (op.returnType == null) {
                    "void"
                } else {
                    JavaTypeMapper.toJavaType(
                        op.returnType!!,
                        dev.kuml.uml.Multiplicity(1, 1),
                    )
                }
            val params =
                op.parameters
                    .filter { it.direction != dev.kuml.uml.ParameterDirection.RETURN }
                    .joinToString(", ") {
                        "${JavaTypeMapper.toJavaType(it.type, dev.kuml.uml.Multiplicity(1, 1))} ${it.name}"
                    }
            sb.appendLine("    $visibility $returnType ${op.name}($params) {")
            sb.appendLine("        throw new UnsupportedOperationException(\"Not implemented yet\");")
            sb.appendLine("    }").appendLine()
        }
    }

    // ── Interface ────────────────────────────────────────────────────────────

    private fun renderInterface(
        iface: UmlInterface,
        packageDir: File,
        pkg: String?,
    ): File {
        val file = File(packageDir, "${iface.name}.java")
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML — do not edit by hand.")
        if (pkg != null) sb.appendLine("package $pkg;").appendLine()
        for (stereo in iface.appliedStereotypes) {
            JavaStereotypeMapper.toAnnotation(stereo)?.let { sb.appendLine(it) }
        }
        sb.appendLine("public interface ${iface.name} {").appendLine()
        for (op in iface.operations) {
            val returnType =
                if (op.returnType == null) {
                    "void"
                } else {
                    JavaTypeMapper.toJavaType(
                        op.returnType!!,
                        dev.kuml.uml.Multiplicity(1, 1),
                    )
                }
            val params =
                op.parameters
                    .filter { it.direction != dev.kuml.uml.ParameterDirection.RETURN }
                    .joinToString(", ") {
                        "${JavaTypeMapper.toJavaType(it.type, dev.kuml.uml.Multiplicity(1, 1))} ${it.name}"
                    }
            sb.appendLine("    $returnType ${op.name}($params);")
        }
        sb.appendLine("}")
        file.writeText(sb.toString())
        return file
    }

    // ── Enum ─────────────────────────────────────────────────────────────────

    private fun renderEnum(
        en: UmlEnumeration,
        packageDir: File,
        pkg: String?,
    ): File {
        val file = File(packageDir, "${en.name}.java")
        val sb = StringBuilder()
        sb.appendLine("// Generated by kUML — do not edit by hand.")
        if (pkg != null) sb.appendLine("package $pkg;").appendLine()
        sb.appendLine("public enum ${en.name} {")
        sb.appendLine(en.literals.joinToString(",\n") { "    ${it.name}" })
        sb.appendLine("}")
        file.writeText(sb.toString())
        return file
    }

    private fun Visibility.toJavaModifier(): String =
        when (this) {
            Visibility.PUBLIC -> "public"
            Visibility.PROTECTED -> "protected"
            Visibility.PRIVATE -> "private"
            Visibility.PACKAGE -> "" // package-private: no modifier
        }
}

internal enum class JavaStyle {
    POJO,
    RECORDS,
    LOMBOK,
    ;

    companion object {
        fun from(raw: String): JavaStyle =
            when (raw.lowercase()) {
                "pojo" -> POJO
                "records", "record" -> RECORDS
                "lombok" -> LOMBOK
                else -> error("Unknown java-style: '$raw'. Allowed: pojo, records, lombok.")
            }
    }
}
