// Generated by kuml-codegen-m2m (uml-to-jpa) — do not edit manually.

package com.example.entities

import jakarta.persistence.*

@Entity
@Table(name = "comments")
data class Comment(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0L,

    @Column(name = "text", nullable = false)
    val text: String = "",
)
