// Generated by kuml-codegen-m2m (uml-to-jpa) — do not edit manually.

package com.example.entities

import jakarta.persistence.*

@Entity
@Table(name = "posts")
data class Post(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0L,

    @Column(name = "title", nullable = false)
    val title: String = "",

    @Column(name = "content", nullable = false)
    val content: String = "",

    @OneToMany(mappedBy = "post", cascade = [CascadeType.ALL], fetch = FetchType.LAZY)
    val comments: List<Comment> = emptyList(),
)
