// Generated by kuml-codegen-m2m (uml-to-jpa) — do not edit manually.

package com.example.entities

import jakarta.persistence.*

@Entity
@Table(name = "users")
data class User(
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    val id: Long = 0L,

    @Column(name = "username", nullable = false)
    val username: String = "",

    @Column(name = "email", nullable = false)
    val email: String = "",
)
