package dev.kuml.cli.structurizr

/**
 * Generates a `.kuml.kts` file from a parsed [StructurizrWorkspace].
 */
internal object KumlDslGenerator {
    internal fun generate(
        workspace: StructurizrWorkspace,
        sourceFileName: String,
    ): String {
        val sb = StringBuilder()

        // Header
        sb.appendLine("// Generated by kuml import --format structurizr")
        sb.appendLine("// Source: $sourceFileName")
        sb.appendLine("// Review and adjust before use.")
        sb.appendLine()
        sb.appendLine("import dev.kuml.c4.dsl.*")
        sb.appendLine("import dev.kuml.c4.model.*")
        sb.appendLine()

        // Collect identifier → variable name mapping
        val varNames = buildVarNames(workspace.model)

        // Pre-declare nullable vars for containers and components (they're nested, but may be
        // referenced in top-level relationships)
        val containerVars = mutableListOf<Pair<String, StructurizrElement.Container>>()
        val componentVars = mutableListOf<Pair<String, StructurizrElement.Component>>()

        for (elem in workspace.model.elements) {
            if (elem is StructurizrElement.SoftwareSystem) {
                for (container in elem.containers) {
                    val id = container.identifier
                    if (id != null) {
                        val varName = varNames[id] ?: continue
                        containerVars += Pair(varName, container)
                        sb.appendLine("var $varName: C4Container? = null")
                    }
                    for (comp in container.components) {
                        val cid = comp.identifier
                        if (cid != null) {
                            val compVarName = varNames[cid] ?: continue
                            componentVars += Pair(compVarName, comp)
                            sb.appendLine("var $compVarName: C4Component? = null")
                        }
                    }
                }
            }
        }

        if (containerVars.isNotEmpty() || componentVars.isNotEmpty()) sb.appendLine()

        // c4Model block
        val modelName = workspace.name.ifBlank { "Workspace" }
        sb.appendLine("c4Model(${modelName.quoted()}) {")

        // Persons
        for (elem in workspace.model.elements) {
            if (elem is StructurizrElement.Person) {
                val varName = elem.identifier?.let { varNames[it] }
                val decl = if (varName != null) "val $varName = " else ""
                sb.append("    ${decl}person(${elem.name.quoted()})")
                val hasBody = elem.description != null || elem.external
                if (hasBody) {
                    sb.appendLine(" {")
                    elem.description?.let { sb.appendLine("        description = ${it.quoted()}") }
                    if (elem.external) sb.appendLine("        external = true")
                    sb.appendLine("    }")
                } else {
                    sb.appendLine()
                }
            }
        }

        // Software Systems
        for (elem in workspace.model.elements) {
            if (elem is StructurizrElement.SoftwareSystem) {
                val varName = elem.identifier?.let { varNames[it] }
                val decl = if (varName != null) "val $varName = " else ""
                sb.append("    ${decl}softwareSystem(${elem.name.quoted()})")
                val hasBody = elem.description != null || elem.external || elem.containers.isNotEmpty()
                if (hasBody) {
                    sb.appendLine(" {")
                    elem.description?.let { sb.appendLine("        description = ${it.quoted()}") }
                    if (elem.external) sb.appendLine("        external = true")
                    for (container in elem.containers) {
                        val cVarName = container.identifier?.let { varNames[it] }
                        val cDecl = if (cVarName != null) "$cVarName = " else ""
                        sb.append("        ${cDecl}container(${container.name.quoted()})")
                        val cHasBody = container.description != null || container.technology != null || container.components.isNotEmpty()
                        if (cHasBody) {
                            sb.appendLine(" {")
                            container.description?.let { sb.appendLine("            description = ${it.quoted()}") }
                            container.technology?.let { sb.appendLine("            technology = ${it.quoted()}") }
                            for (comp in container.components) {
                                val compVarName = comp.identifier?.let { varNames[it] }
                                val compDecl = if (compVarName != null) "$compVarName = " else ""
                                sb.append("            ${compDecl}component(${comp.name.quoted()})")
                                val compHasBody = comp.description != null || comp.technology != null
                                if (compHasBody) {
                                    sb.appendLine(" {")
                                    comp.description?.let { sb.appendLine("                description = ${it.quoted()}") }
                                    comp.technology?.let { sb.appendLine("                technology = ${it.quoted()}") }
                                    sb.appendLine("            }")
                                } else {
                                    sb.appendLine()
                                }
                            }
                            sb.appendLine("        }")
                        } else {
                            sb.appendLine()
                        }
                    }
                    sb.appendLine("    }")
                } else {
                    sb.appendLine()
                }
            }
        }

        // Deployment nodes
        for (elem in workspace.model.elements) {
            if (elem is StructurizrElement.DeploymentNode) {
                sb.append(generateDeploymentNode(elem, varNames, indent = "    "))
            }
        }

        // Relationships
        for (rel in workspace.model.relationships) {
            val sourceVar = resolveVar(rel.sourceIdentifier, varNames)
            val targetVar = resolveVar(rel.targetIdentifier, varNames)

            if (sourceVar == null || targetVar == null) {
                sb.appendLine("    // TODO: relationship ${rel.sourceIdentifier} -> ${rel.targetIdentifier}")
                continue
            }

            val srcExpr = if (isNullableVar(rel.sourceIdentifier, workspace)) "$sourceVar!!" else sourceVar
            val tgtExpr = if (isNullableVar(rel.targetIdentifier, workspace)) "$targetVar!!" else targetVar

            val hasBody = rel.technology != null
            sb.append("    relationship($srcExpr, $tgtExpr)")
            if (hasBody) {
                sb.appendLine(" {")
                // Note: Structurizr description maps to the relationship label, not editable in kUML DSL
                rel.description?.let { sb.appendLine("        // label: $it") }
                sb.appendLine("        technology = ${rel.technology.quoted()}")
                sb.appendLine("    }")
            } else {
                if (rel.description != null) {
                    sb.appendLine(" { /* label: ${rel.description} */ }")
                } else {
                    sb.appendLine()
                }
            }
        }

        // Views
        val viewsSection = generateViews(workspace, varNames)
        if (viewsSection.isNotBlank()) {
            sb.appendLine()
            sb.append(viewsSection)
        }

        sb.appendLine("}")

        return sb.toString()
    }

    // ─── Variable name mapping ─────────────────────────────────────────────────

    private fun buildVarNames(model: StructurizrModel): Map<String, String> {
        val result = mutableMapOf<String, String>()
        var personCounter = 0
        var systemCounter = 0
        var containerCounter = 0
        var componentCounter = 0
        var nodeCounter = 0

        fun register(
            identifier: String?,
            prefix: String,
            counter: () -> Int,
        ): String {
            val base = if (identifier != null) sanitizeIdentifier(identifier) else "$prefix${counter()}"
            // Ensure uniqueness
            var candidate = base
            var n = 2
            while (result.values.contains(candidate)) {
                candidate = "${base}_$n"
                n++
            }
            if (identifier != null) result[identifier] = candidate
            return candidate
        }

        for (elem in model.elements) {
            when (elem) {
                is StructurizrElement.Person -> {
                    personCounter++
                    val v = register(elem.identifier, "person", { personCounter })
                    if (elem.identifier == null) { // no-op, not tracked
                    } else {
                        result[elem.identifier] = v
                    }
                }
                is StructurizrElement.SoftwareSystem -> {
                    systemCounter++
                    val v = register(elem.identifier, "system", { systemCounter })
                    if (elem.identifier != null) result[elem.identifier] = v
                    for (container in elem.containers) {
                        containerCounter++
                        val cv = register(container.identifier, "container", { containerCounter })
                        if (container.identifier != null) result[container.identifier] = cv
                        for (comp in container.components) {
                            componentCounter++
                            val compV = register(comp.identifier, "component", { componentCounter })
                            if (comp.identifier != null) result[comp.identifier] = compV
                        }
                    }
                }
                is StructurizrElement.Container -> {
                    containerCounter++
                    val v = register(elem.identifier, "container", { containerCounter })
                    if (elem.identifier != null) result[elem.identifier] = v
                }
                is StructurizrElement.Component -> {
                    componentCounter++
                    val v = register(elem.identifier, "component", { componentCounter })
                    if (elem.identifier != null) result[elem.identifier] = v
                }
                is StructurizrElement.DeploymentNode -> {
                    nodeCounter++
                    val v = register(elem.identifier, "node", { nodeCounter })
                    if (elem.identifier != null) result[elem.identifier] = v
                }
            }
        }
        return result
    }

    private fun sanitizeIdentifier(raw: String): String {
        // Remove hierarchical dot notation (take last segment)
        val last = raw.substringAfterLast('.')
        // Replace non-alphanumeric with underscore, ensure starts with letter
        val cleaned = last.replace(Regex("[^a-zA-Z0-9_]"), "_")
        return if (cleaned.isNotEmpty() && cleaned[0].isDigit()) "_$cleaned" else cleaned.ifEmpty { "elem" }
    }

    private fun resolveVar(
        identifier: String,
        varNames: Map<String, String>,
    ): String? {
        // Try direct lookup
        varNames[identifier]?.let { return it }
        // Try stripping hierarchical prefix
        val last = identifier.substringAfterLast('.')
        return varNames[last] ?: varNames.entries.firstOrNull { it.key.endsWith(".$identifier") || it.key == identifier }?.value
    }

    private fun isNullableVar(
        identifier: String,
        workspace: StructurizrWorkspace,
    ): Boolean {
        // Containers and components declared inside systems are pre-declared as var ...: Type? = null
        for (elem in workspace.model.elements) {
            if (elem is StructurizrElement.SoftwareSystem) {
                for (container in elem.containers) {
                    if (container.identifier == identifier) return true
                    for (comp in container.components) {
                        if (comp.identifier == identifier) return true
                    }
                }
            }
        }
        return false
    }

    // ─── Deployment nodes ─────────────────────────────────────────────────────

    private fun generateDeploymentNode(
        node: StructurizrElement.DeploymentNode,
        varNames: Map<String, String>,
        indent: String,
    ): String {
        val sb = StringBuilder()
        val varName = node.identifier?.let { varNames[it] }
        val decl = if (varName != null) "val $varName = " else ""
        sb.append("${indent}${decl}deploymentNode(${node.name.quoted()})")
        val hasBody = node.description != null || node.technology != null || node.children.isNotEmpty()
        if (hasBody) {
            sb.appendLine(" {")
            node.description?.let { sb.appendLine("$indent    description = ${it.quoted()}") }
            node.technology?.let { sb.appendLine("$indent    technology = ${it.quoted()}") }
            for (child in node.children) {
                sb.append(generateDeploymentNode(child, varNames, "$indent    "))
            }
            sb.appendLine("$indent}")
        } else {
            sb.appendLine()
        }
        return sb.toString()
    }

    // ─── Views ────────────────────────────────────────────────────────────────

    private fun generateViews(
        workspace: StructurizrWorkspace,
        varNames: Map<String, String>,
    ): String {
        val sb = StringBuilder()
        val views = workspace.views.views

        if (views.isEmpty()) {
            // Auto-generate default views
            val systems = workspace.model.elements.filterIsInstance<StructurizrElement.SoftwareSystem>()
            for (system in systems) {
                sb.appendLine("    systemContextDiagram(${system.name.quoted()}) { }")
                if (system.containers.isNotEmpty()) {
                    sb.appendLine("    containerDiagram(${(system.name + " — Containers").quoted()}) { }")
                }
            }
        } else {
            for (view in views) {
                when (view) {
                    is StructurizrView.SystemContext -> {
                        val title = view.description ?: view.key ?: "System Context"
                        sb.appendLine("    systemContextDiagram(${title.quoted()}) { }")
                    }
                    is StructurizrView.Container -> {
                        val title = view.description ?: view.key ?: "Containers"
                        sb.appendLine("    containerDiagram(${title.quoted()}) { }")
                    }
                    is StructurizrView.Component -> {
                        val title = view.description ?: view.key ?: "Components"
                        sb.appendLine("    componentDiagram(${title.quoted()}) { }")
                    }
                    is StructurizrView.Deployment -> {
                        val title = view.description ?: view.key ?: "Deployment"
                        sb.appendLine("    deploymentDiagram(${title.quoted()}) { }")
                    }
                    is StructurizrView.SystemLandscape -> {
                        val title = view.description ?: view.key ?: "System Landscape"
                        sb.appendLine("    systemLandscapeDiagram(${title.quoted()}) { }")
                    }
                }
            }
        }

        return sb.toString()
    }

    // ─── Helpers ──────────────────────────────────────────────────────────────

    private fun String.quoted(): String {
        val escaped = this.replace("\\", "\\\\").replace("\"", "\\\"")
        return "\"$escaped\""
    }
}
