package dev.kuml.vaultexamples

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldNotBe
import java.io.File
import java.nio.file.Paths

class VaultExamplesRenderTest :
    StringSpec({
        val examples = VaultExampleLoader.loadFromClasspath()

        // Examples with known issues can be listed here to avoid failing the test run.
        // (The 00 Übersicht.md file contains no kuml blocks so it never appears here.)
        val skipExamples = setOf<String>()

        if (examples.isEmpty()) {
            println(
                "[vault-examples] Keine Beispiele auf dem Classpath gefunden. " +
                    "Stelle sicher, dass src/test/resources/vault-examples/ befüllt ist " +
                    "(via scripts/sync-vault-examples.sh).",
            )
        } else {
            println("[vault-examples] ${examples.size} Beispiele vom Classpath geladen")

            examples.forEach { example ->
                "rendert ${example.baseName}" {
                    val baseName = "vault-examples/${example.sanitizedName}"

                    if (example.sanitizedName !in skipExamples) {
                        val result = VaultExampleRenderer.render(example.kumlScript)

                        if (result.svg != null) {
                            SampleOutput.write("$baseName.svg", result.svg)
                        }
                        if (result.latex != null) {
                            SampleOutput.write("$baseName.tex", result.latex)
                        }

                        if (result.error != null) {
                            println("[vault-examples] FEHLER bei ${example.baseName}: ${result.error}")
                        }

                        // At least one output must be present (SVG or LaTeX)
                        (result.svg ?: result.latex) shouldNotBe null
                    } else {
                        println("[vault-examples] Übersprungen: ${example.baseName}")
                    }
                }
            }

            // ── Index generation ─────────────────────────────────────────────
            // After all tests run, write a Markdown index mapping every vault
            // example to its test case name and sanitized output base. This is
            // done in afterSpec rather than via a Gradle task to avoid the
            // Gradle 9 configuration-cache issue with script-object references.
            afterSpec {
                writeVaultExamplesIndex(examples)
            }
        }
    })

/**
 * Writes build/sample-output/vault-examples-index.md describing the mapping
 * between vault .md files, their test case names, and the sanitized output
 * file basenames. Re-run alongside the test suite, so the index always
 * reflects the current state of the synced examples.
 */
private fun writeVaultExamplesIndex(examples: List<VaultExample>) {
    val outputBase = Paths.get(System.getProperty("user.dir")).resolve("build/sample-output/vault-examples")

    val sb = StringBuilder()
    sb.appendLine("# Vault Examples — Test/Output Index")
    sb.appendLine()
    sb.appendLine("Auto-generated by `VaultExamplesRenderTest` (afterSpec hook).")
    sb.appendLine()
    sb.appendLine("Each vault example below produces one test case in")
    sb.appendLine("`VaultExamplesRenderTest` and one set of SVG / PNG / TEX files")
    sb.appendLine("under `build/sample-output/vault-examples/`.")
    sb.appendLine()
    sb.appendLine("Source: `src/test/resources/vault-examples/` (synced from the Obsidian vault via `scripts/sync-vault-examples.sh`).")
    sb.appendLine()
    sb.appendLine("| Vault Example (.md) | Test Case Name | Sanitized Output Base | Output Files |")
    sb.appendLine("|---|---|---|---|")

    // Group examples by source filename so multi-block files appear together.
    val grouped = examples.groupBy { it.fileName }
    for ((fileName, group) in grouped.entries.sortedBy { it.key }) {
        if (group.size == 1) {
            val ex = group.first()
            val outputs = listOutputs(outputBase.toFile(), ex.sanitizedName)
            sb.appendLine("| $fileName | `rendert ${ex.baseName}` | `${ex.sanitizedName}` | $outputs |")
        } else {
            group.forEachIndexed { idx, ex ->
                val outputs = listOutputs(outputBase.toFile(), ex.sanitizedName)
                sb.appendLine("| $fileName (block $idx) | `rendert ${ex.baseName}` | `${ex.sanitizedName}` | $outputs |")
            }
        }
    }
    sb.appendLine()
    sb.appendLine("**Output formats per example:**")
    sb.appendLine("- `<base>.svg` — SVG (always)")
    sb.appendLine("- `<base>.png` — PNG (auto-generated next to SVG by `SampleOutput`)")
    sb.appendLine("- `<base>.tex` — LaTeX/TikZ (only where `KumlLatexRenderer` supports the diagram type — UML + SysML 2, **not** C4)")

    val indexFile =
        Paths
            .get(System.getProperty("user.dir"))
            .resolve("build/sample-output/vault-examples-index.md")
            .toFile()
    indexFile.parentFile.mkdirs()
    indexFile.writeText(sb.toString())
    println("[vault-examples-index] $indexFile")
}

private fun listOutputs(
    baseDir: File,
    sanitizedBase: String,
): String =
    listOf("svg", "png", "tex")
        .filter { ext -> File(baseDir, "$sanitizedBase.$ext").exists() }
        .joinToString(", ") { ext -> ".$ext" }
        .ifEmpty { "—" }
