package dev.kuml.vaultexamples

import dev.kuml.renderer.theme.core.ThemeRegistry
import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldNotBe
import java.io.File
import java.nio.file.Paths

class VaultExamplesRenderTest :
    StringSpec({
        val examples = VaultExampleLoader.loadFromClasspath()

        // Examples with known issues can be listed here to avoid failing the test run.
        // (The 00 Übersicht.md file contains no kuml blocks so it never appears here.)
        val skipExamples = setOf<String>()

        if (examples.isEmpty()) {
            println(
                "[vault-examples] Keine Beispiele auf dem Classpath gefunden. " +
                    "Stelle sicher, dass src/test/resources/vault-examples/ befüllt ist " +
                    "(via scripts/sync-vault-examples.sh).",
            )
        } else {
            // Ensure ThemeRegistry is populated before we query available themes.
            VaultExampleRenderer.init()
            val themes = ThemeRegistry.names().ifEmpty { listOf("elegant") }

            println("[vault-examples] ${examples.size} Beispiele vom Classpath geladen")
            println("[vault-examples] Verfügbare Themes: $themes")

            examples.forEach { example ->
                "rendert ${example.baseName}" {
                    if (example.sanitizedName !in skipExamples) {
                        var atLeastOneSvg = false

                        // ── SVG + PNG: einmal pro Theme, in theme-spezifischem Unterverzeichnis ──
                        for (themeName in themes) {
                            val result = VaultExampleRenderer.render(example.kumlScript, themeName)
                            val baseName = "vault-examples/$themeName/${example.sanitizedName}"

                            if (result.svg != null) {
                                SampleOutput.write("$baseName.svg", result.svg)
                                atLeastOneSvg = true
                            }

                            if (result.error != null) {
                                println(
                                    "[vault-examples/$themeName] FEHLER bei ${example.baseName}: ${result.error}",
                                )
                            }
                        }

                        // ── LaTeX: theme-unabhängig, einmalig unter vault-examples/latex/ ──
                        val latexResult = VaultExampleRenderer.render(example.kumlScript, themes.first())
                        if (latexResult.latex != null) {
                            SampleOutput.write(
                                "vault-examples/latex/${example.sanitizedName}.tex",
                                latexResult.latex,
                            )
                        }

                        // At least one SVG must have been produced
                        atLeastOneSvg shouldNotBe false
                    } else {
                        println("[vault-examples] Übersprungen: ${example.baseName}")
                    }
                }
            }

            // ── Index generation ─────────────────────────────────────────────
            afterSpec {
                writeVaultExamplesIndex(examples, themes)
            }
        }
    })

/**
 * Writes build/sample-output/vault-examples-index.md with a per-theme breakdown
 * of which examples rendered successfully.
 */
private fun writeVaultExamplesIndex(
    examples: List<VaultExample>,
    themes: List<String>,
) {
    val outputBase = Paths.get(System.getProperty("user.dir")).resolve("build/sample-output/vault-examples")

    val sb = StringBuilder()
    sb.appendLine("# Vault Examples — Test/Output Index")
    sb.appendLine()
    sb.appendLine("Auto-generated by `VaultExamplesRenderTest` (afterSpec hook).")
    sb.appendLine()
    sb.appendLine("Each vault example is rendered in **${themes.size} theme(s)**: ${themes.joinToString(", ")}.")
    sb.appendLine()
    sb.appendLine("## Output structure")
    sb.appendLine()
    sb.appendLine("```")
    sb.appendLine("build/sample-output/vault-examples/")
    themes.forEach { theme -> sb.appendLine("  $theme/          ← SVG + PNG for theme '$theme'") }
    sb.appendLine("  latex/           ← LaTeX/TikZ (theme-independent)")
    sb.appendLine("```")
    sb.appendLine()
    sb.appendLine("## Examples")
    sb.appendLine()
    sb.appendLine("| Vault Example (.md) | Test Case | Output Base | Themes | LaTeX |")
    sb.appendLine("|---|---|---|---|---|")

    val grouped = examples.groupBy { it.fileName }
    for ((fileName, group) in grouped.entries.sortedBy { it.key }) {
        val rows = if (group.size == 1) listOf(group.first() to "") else group.mapIndexed { i, e -> e to " (block $i)" }
        for ((ex, suffix) in rows) {
            val themeMarks =
                themes.joinToString(", ") { theme ->
                    val ok = File(outputBase.toFile(), "$theme/${ex.sanitizedName}.svg").exists()
                    if (ok) "✅ $theme" else "❌ $theme"
                }
            val hasLatex = File(outputBase.toFile(), "latex/${ex.sanitizedName}.tex").exists()
            sb.appendLine(
                "| $fileName$suffix | `rendert ${ex.baseName}` | `${ex.sanitizedName}` | $themeMarks | ${if (hasLatex) "✅" else "—"} |",
            )
        }
    }

    val indexFile =
        Paths
            .get(System.getProperty("user.dir"))
            .resolve("build/sample-output/vault-examples-index.md")
            .toFile()
    indexFile.parentFile.mkdirs()
    indexFile.writeText(sb.toString())
    println("[vault-examples-index] $indexFile")
}
