#!/usr/bin/env bash
# build-handbook.sh
#
# Pre-renders `[source,kuml]` blocks and `kuml::path[]` macros in the Antora
# handbook to inline-linked SVGs, then runs Antora against the pre-rendered
# copy. This is the bridge described in
# docs/handbook/modules/tooling/pages/asciidoc.adoc: Antora runs on
# Asciidoctor.js (Node) and cannot load the JVM `kuml-asciidoc` Asciidoctor
# extension directly, so `kuml asciidoc` renders the diagrams to plain
# AsciiDoc *before* Antora ever sees the files (V3.2.19).
#
# Antora content sources must be git repositories (a plain directory does
# not work — verified empirically). This script therefore stages the
# pre-rendered handbook tree into a disposable scratch git repo under
# build/handbook-rendered/ and points a generated playbook at that repo.
# The *committed* repo (docs/handbook/**/*.adoc) is untouched — it keeps
# the raw `[source,kuml]` DSL source, never pre-rendered SVGs, per the
# "diagram source belongs in the document" convention.
#
# Usage:
#   scripts/build-handbook.sh              # build the site into build/site
#   scripts/build-handbook.sh --open       # build and open build/site/index.html (macOS)
#
# Environment overrides:
#   KUML_BIN  — path to the kuml CLI binary (default: kuml-cli/build/install/kuml/bin/kuml,
#               falls back to `kuml` on PATH if the local build is missing)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

LOCAL_KUML="$REPO_ROOT/kuml-cli/build/install/kuml/bin/kuml"
if [ -x "${KUML_BIN:-}" ]; then
  KUML="$KUML_BIN"
elif [ -x "$LOCAL_KUML" ]; then
  KUML="$LOCAL_KUML"
elif command -v kuml >/dev/null 2>&1; then
  KUML="$(command -v kuml)"
else
  echo "[build-handbook] No kuml CLI found. Run './gradlew clean :kuml-cli:installDist' first" >&2
  echo "[build-handbook] (or set KUML_BIN to an existing binary)." >&2
  exit 1
fi

STAGE_DIR="$REPO_ROOT/build/handbook-rendered"
SITE_DIR="$REPO_ROOT/build/site"
SCRATCH_PLAYBOOK="$REPO_ROOT/build/antora-playbook.rendered.yml"

echo "[build-handbook] Using kuml CLI: $KUML"
echo "[build-handbook] Pre-rendering docs/handbook -> $STAGE_DIR/docs/handbook"
rm -rf "$STAGE_DIR"
mkdir -p "$STAGE_DIR"
"$KUML" asciidoc \
  --input-dir "$REPO_ROOT/docs/handbook" \
  --output-dir "$STAGE_DIR/docs/handbook" \
  --mode linked-svg

echo "[build-handbook] Staging scratch git repo for Antora (content sources must be git repos)"
git -C "$STAGE_DIR" init -q
git -C "$STAGE_DIR" add -A
git -C "$STAGE_DIR" -c user.email="kuml-build@localhost" -c user.name="kUML Handbook Build" \
  commit -q -m "Pre-rendered handbook (scratch, not for publishing)"

cat > "$SCRATCH_PLAYBOOK" << EOF
# Generated by scripts/build-handbook.sh — do not edit, do not commit.
# Points at the pre-rendered scratch repo in build/handbook-rendered/.
site:
  title: kUML Handbook
  url: https://docs.kuml.dev
  start_page: kuml::index.adoc

content:
  sources:
    - url: $STAGE_DIR
      branches: HEAD
      start_path: docs/handbook

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: $SITE_DIR

asciidoc:
  attributes:
    page-toclevels: 3
    source-highlighter: highlight.js
EOF

echo "[build-handbook] Running Antora"
npx antora generate "$SCRATCH_PLAYBOOK"

echo "[build-handbook] Done. Site: $SITE_DIR/index.html"

if [ "${1:-}" = "--open" ] && command -v open >/dev/null 2>&1; then
  open "$SITE_DIR/index.html"
fi
