#!/usr/bin/env bash
# sync-vault-examples.sh
#
# Syncs the kUML example notes from the Obsidian vault into two targets:
#   1. kuml-tests/kuml-vault-examples-tests/src/test/resources/vault-examples/
#      → consumed by VaultExamplesRenderTest as classpath resources (CI-safe).
#   2. /Users/irakli/WebstormProjects/kuml.dev/playground-sources/
#      → each ` ```kuml ` fenced block is extracted into a .kuml.kts file
#        (only when content actually changed, to avoid noisy commits).
#
# The Obsidian vault is the source of truth. Run this script after editing
# any example note in the vault. A separate watch script (watch-vault-examples.sh)
# can call this on file system events.
#
# Idempotent: produces no diff when content is unchanged.
#
# Usage:
#   scripts/sync-vault-examples.sh
#
# Environment overrides:
#   VAULT_EXAMPLES_DIR  — vault source dir (default: ~/Documents/Obsidian/Zweites Gehirn/03 Bereiche/kUML/Beispiele)
#   KUML_DEV_DIR        — kuml.dev repo root  (default: ~/WebstormProjects/kuml.dev)

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

VAULT_EXAMPLES_DIR="${VAULT_EXAMPLES_DIR:-$HOME/Documents/Obsidian/Zweites Gehirn/03 Bereiche/kUML/Beispiele}"
KUML_DEV_DIR="${KUML_DEV_DIR:-$HOME/WebstormProjects/kuml.dev}"

REPO_TARGET="$REPO_ROOT/kuml-tests/kuml-vault-examples-tests/src/test/resources/vault-examples"
WEB_TARGET="$KUML_DEV_DIR/playground-sources"

# ── Mapping from vault filename to webseite playground filename ─────────────
# Webseite uses kebab-case .kuml.kts names. Add new mappings here as new vault
# examples are introduced. Unmapped vault examples are still synced to the
# repo target — they just don't appear on the webseite until mapped.
#
# Implemented as a case statement instead of associative array, since
# macOS ships bash 3.x which does not support `declare -A`.
map_vault_to_web() {
  case "$1" in
    "01 UML Klasse – Order Domain.md")            echo "uml-class-order-domain.kuml.kts" ;;
    "02 C4 Container – Internet Banking.md")      echo "c4-container-banking.kuml.kts" ;;
    "03 SysML 2 BDD – Hybrid Vehicle.md")         echo "sysml2-hybrid-vehicle.kuml.kts" ;;
    "04 SysML 2 STM – Traffic Light.md")          echo "sysml2-traffic-light-stm.kuml.kts" ;;
    "05 SysML 2 UC – Library System.md")          echo "sysml2-library-system-uc.kuml.kts" ;;
    "06 SysML 2 SEQ – Login Flow.md")             echo "sysml2-login-flow-seq.kuml.kts" ;;
    "07 SysML 2 ACT – Order Processing.md")       echo "sysml2-order-processing-act.kuml.kts" ;;
    "08 SysML 2 REQ – Vehicle Requirements.md")   echo "sysml2-vehicle-requirements.kuml.kts" ;;
    "09 C4 Landscape – Enterprise Banking.md")    echo "c4-landscape-enterprise-banking.kuml.kts" ;;
    "12 UML Component – Order Architecture.md")   echo "uml-component-architecture.kuml.kts" ;;
    "13 UML Composite Structure – Order Internals.md") echo "uml-composite-payment-service.kuml.kts" ;;
    "17 UML Activity – Checkout Flow.md")         echo "uml-activity-order-checkout.kuml.kts" ;;
    "20 UML Communication – Place Order.md")      echo "uml-communication-checkout.kuml.kts" ;;
    "23 C4 Context – Internet Banking.md")        echo "c4-context-internet-banking.kuml.kts" ;;
    "28 SysML 2 PAR – Newton.md")                 echo "sysml2-newton-second-law-par.kuml.kts" ;;
    "33 Blueprint – PdV Mitglieder-Journey.md")   echo "blueprint-pdv-mitglieder-journey.kuml.kts" ;;
    *)                                            echo "" ;;
  esac
}

# ── 1. Sync .md files into the Gradle test-resources directory ──────────────

if [[ ! -d "$VAULT_EXAMPLES_DIR" ]]; then
  echo "[sync] Vault directory not found: $VAULT_EXAMPLES_DIR" >&2
  exit 1
fi

mkdir -p "$REPO_TARGET"

# Use rsync for atomic content-aware sync — only changed files trigger writes.
# --delete makes the repo target a strict mirror of the vault (no orphans).
rsync -a --delete --include="*.md" --exclude="*" \
  "$VAULT_EXAMPLES_DIR/" "$REPO_TARGET/"

# Generate the _files.txt manifest so VaultExampleLoader can enumerate the
# resources at runtime (classpath cannot be listed directly from a JAR).
manifest="$REPO_TARGET/_files.txt"
{
  echo "# Auto-generated by scripts/sync-vault-examples.sh — do not edit by hand."
  echo "# One vault example filename per line. Used by VaultExampleLoader at runtime."
  cd "$REPO_TARGET" && find . -maxdepth 1 -type f -name "*.md" -exec basename {} \; | LC_ALL=C sort
} > "$manifest"

echo "[sync] Repo target updated: $REPO_TARGET ($(grep -cv '^#' "$manifest") example(s))"

# ── 2. Sync vault → kuml.dev/playground-sources (extract kuml fenced blocks) ──

if [[ ! -d "$KUML_DEV_DIR" ]]; then
  echo "[sync] kuml.dev directory not found — skipping webseite sync: $KUML_DEV_DIR"
  exit 0
fi

mkdir -p "$WEB_TARGET"

web_count=0
for vault_file in "$VAULT_EXAMPLES_DIR"/*.md; do
  filename="$(basename "$vault_file")"
  web_name="$(map_vault_to_web "$filename")"
  if [ -z "$web_name" ]; then
    continue   # not in the mapping table → skip the webseite write
  fi

  # Extract the first ` ```kuml ` fenced block via awk (portable on macOS bash 3).
  extracted="$(awk '
    /^```kuml/ { in_block=1; next }
    in_block && /^```/  { in_block=0; exit }
    in_block            { print }
  ' "$vault_file")"

  if [ -z "$extracted" ]; then
    continue
  fi

  target_file="$WEB_TARGET/$web_name"
  if [ -f "$target_file" ] && cmp -s <(printf '%s\n' "$extracted") "$target_file"; then
    continue   # already up to date, do not touch mtime
  fi

  printf '%s\n' "$extracted" > "$target_file"
  web_count=$((web_count + 1))
done

echo "[sync] Webseite target updated: $WEB_TARGET ($web_count file(s) refreshed)"
