package dev.kuml.io.svg

import dev.kuml.core.model.KumlDiagram
import dev.kuml.layout.LayoutEngineId
import dev.kuml.layout.LayoutResult
import dev.kuml.layout.NodeId
import dev.kuml.layout.NodeLayout
import dev.kuml.layout.Point
import dev.kuml.layout.Rect
import dev.kuml.layout.Size
import dev.kuml.renderer.theme.core.PlainTheme
import dev.kuml.uml.UmlClass
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.shouldBe
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

/**
 * "Powered by kUML" branding — covers both channels emitted by
 * [SvgDocument.render]:
 *
 *  - the always-on "Generated by kUML v…" XML comment (every SVG, every
 *    surface, regardless of [SvgRenderOptions.embedThemeAsComment]);
 *  - the opt-in visible watermark ([SvgRenderOptions.watermark]), off by
 *    default, themed via the theme's `small`/`muted` role, and never
 *    overlapping diagram content.
 */
class SvgBrandingTest :
    FunSpec({

        fun minimalDiagram() = KumlDiagram(name = "Test", elements = listOf(UmlClass(id = "cls1", name = "Order")))

        fun minimalLayout() =
            LayoutResult(
                engineId = LayoutEngineId("test"),
                seed = 1L,
                canvas = Size(300f, 200f),
                nodes = mapOf(NodeId("cls1") to NodeLayout(bounds = Rect(Point(10f, 10f), Size(120f, 80f)))),
                edges = emptyMap(),
                groups = emptyMap(),
            )

        // ── A. Always-on attribution comment ───────────────────────────────

        test("every SVG carries the 'Generated by kUML' attribution comment by default") {
            val svg = KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), PlainTheme())
            svg shouldContain "<!-- Generated by kUML v"
            svg shouldContain "— kuml.dev -->"
        }

        test("the attribution version matches KumlBuildInfo.VERSION and looks like a semver") {
            val svg = KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), PlainTheme())
            val match = Regex("""Generated by kUML v([^ ]+) """).find(svg)
            match shouldBe match // sanity: regex must have matched (non-null)
            val version = match?.groupValues?.get(1)
            version shouldBe KumlBuildInfo.VERSION
            Regex("""^\d+\.\d+\.\d+""").containsMatchIn(KumlBuildInfo.VERSION) shouldBe true
        }

        test("attribution comment is independent of embedThemeAsComment=false") {
            val svg =
                KumlSvgRenderer.toSvg(
                    minimalDiagram(),
                    minimalLayout(),
                    PlainTheme(),
                    SvgRenderOptions(embedThemeAsComment = false),
                )
            // The theme/engine debug comment is gone...
            svg shouldNotContain "kUML SVG · theme:"
            // ...but the attribution comment survives regardless.
            svg shouldContain "<!-- Generated by kUML v"
        }

        test("attribution comment is present alongside the theme comment when both are on") {
            val svg =
                KumlSvgRenderer.toSvg(
                    minimalDiagram(),
                    minimalLayout(),
                    PlainTheme(),
                    SvgRenderOptions(embedThemeAsComment = true),
                )
            svg shouldContain "<!-- Generated by kUML v"
            svg shouldContain "kUML SVG · theme:"
        }

        // ── B. Watermark default-off ────────────────────────────────────────

        test("watermark is off by default — no visible 'Powered by kUML' text") {
            val svg = KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), PlainTheme())
            svg shouldNotContain "Powered by kUML"
        }

        test("SvgRenderOptions.DEFAULT has watermark=false") {
            SvgRenderOptions.DEFAULT.watermark shouldBe false
        }

        // ── C. Watermark explicit-on ─────────────────────────────────────────

        test("watermark=true renders a themed, right-aligned 'Powered by kUML' text") {
            val theme = PlainTheme()
            val svg =
                KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), theme, SvgRenderOptions(watermark = true))
            svg shouldContain "Powered by kUML"
            svg shouldContain """text-anchor="end""""
            svg shouldContain """font-family="${theme.typography.small.family}""""
            svg shouldContain theme.colors.muted.toHex()
        }

        test("watermark=true grows the canvas height but not width for a normally-sized diagram") {
            val plain = KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), PlainTheme())
            val withWatermark =
                KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), PlainTheme(), SvgRenderOptions(watermark = true))

            fun height(svg: String) = Regex("""<svg[^>]*\bheight="([0-9.]+)"""").find(svg)!!.groupValues[1].toFloat()

            fun width(svg: String) = Regex("""<svg[^>]*\bwidth="([0-9.]+)"""").find(svg)!!.groupValues[1].toFloat()

            (height(withWatermark) > height(plain)) shouldBe true
            width(withWatermark) shouldBe width(plain)
        }

        test("watermark=true widens a pathologically narrow canvas so the label is never clipped") {
            val tinyLayout =
                LayoutResult(
                    engineId = LayoutEngineId("test"),
                    seed = 1L,
                    canvas = Size(20f, 20f),
                    nodes = mapOf(NodeId("cls1") to NodeLayout(bounds = Rect(Point(0f, 0f), Size(20f, 20f)))),
                    edges = emptyMap(),
                    groups = emptyMap(),
                )
            val svg = KumlSvgRenderer.toSvg(minimalDiagram(), tinyLayout, PlainTheme(), SvgRenderOptions(watermark = true))
            val width = Regex("""<svg[^>]*\bwidth="([0-9.]+)"""").find(svg)!!.groupValues[1].toFloat()
            // "Powered by kUML" (15 chars) at the theme's small font size must fit
            // with room either side — a canvas as narrow as the un-widened 20px+2*padding
            // content box would clip the right-aligned label.
            (width > 60f) shouldBe true
        }

        test("watermark baseline sits strictly below the content region — cannot overlap a node") {
            val layout = minimalLayout()
            val options = SvgRenderOptions(watermark = true)
            val svg = KumlSvgRenderer.toSvg(minimalDiagram(), layout, PlainTheme(), options)
            val watermarkY = Regex("""<text[^>]*\by="([0-9.]+)"[^>]*text-anchor="end"""").find(svg)!!.groupValues[1].toFloat()
            val contentBottom = layout.canvas.height + 2 * options.paddingPx
            (watermarkY > contentBottom) shouldBe true
        }

        test("watermark text is drawn after (on top of) the nodes/edges groups") {
            val svg =
                KumlSvgRenderer.toSvg(minimalDiagram(), minimalLayout(), PlainTheme(), SvgRenderOptions(watermark = true))
            val edgesCloseIdx = svg.indexOf("</g>", svg.indexOf("<g id=\"edges\">"))
            val watermarkIdx = svg.indexOf("Powered by kUML")
            (watermarkIdx > edgesCloseIdx) shouldBe true
        }
    })
