package dev.kuml.io.svg

import dev.kuml.layout.LayoutResult
import dev.kuml.renderer.theme.core.KumlTheme

/**
 * Baut das SVG-Wurzel-Dokument mit `<defs>`, `<style>`, `<g id="nodes">` und
 * `<g id="edges">` auf.
 *
 * Die eigentliche Node- und Edge-Bestückung erfolgt durch die Aufrufer-Callbacks.
 *
 * Beispiel:
 * ```kotlin
 * val svg = SvgDocument.render(layoutResult, theme, options) { nodeGroup, edgeGroup ->
 *     nodeGroup.tag("rect", ...)
 *     edgeGroup.tag("line", ...)
 * }
 * ```
 */
internal object SvgDocument {
    // "Powered by kUML" branding — watermark geometry constants. See the
    // property-level KDoc on SvgRenderOptions.watermark for the opt-in
    // contract; this text/comment pair is the sole place both branding
    // channels are actually emitted, since every `toSvg`/`toSvgFile` overload
    // funnels through this function.
    private const val ATTRIBUTION_PREFIX = "Generated by kUML v"
    private const val ATTRIBUTION_SUFFIX = " — kuml.dev"
    private const val WATERMARK_TEXT = "Powered by kUML"

    // Extra canvas height reserved below the existing bottom padding when the
    // watermark is on — a small-font text line plus a little breathing room.
    private const val WATERMARK_BAND_PX = 18f

    // Gap between the bottom of the (grown) canvas and the watermark baseline.
    private const val WATERMARK_GAP_PX = 6f

    // Per-character width heuristic for the small/muted theme font, in the
    // same spirit as BODY_CHAR_WIDTH used elsewhere in the renderer (no font-
    // metrics engine is available in commonMain). Deliberately generous so the
    // narrow-canvas guard never under-sizes and clips the label.
    private const val WATERMARK_CHAR_WIDTH_FACTOR = 0.62f

    /**
     * The always-on "Generated by kUML v…" XML comment. Exposed (not just
     * inlined in [render]) so the one renderer that bypasses [render]'s
     * `<svg>` assembly — Blueprint's `renderBlueprintJourney`, which builds
     * its own root `<svg>` tag via deterministic grid geometry rather than a
     * [dev.kuml.layout.LayoutResult] — can still emit the same attribution.
     */
    internal fun attributionComment(): String = "<!-- $ATTRIBUTION_PREFIX${KumlBuildInfo.VERSION}$ATTRIBUTION_SUFFIX -->"

    fun render(
        layoutResult: LayoutResult,
        theme: KumlTheme,
        options: SvgRenderOptions,
        frameName: String? = null,
        frameTypeLabel: String? = null,
        populate: (nodes: SvgBuilder, edges: SvgBuilder) -> Unit,
    ): String {
        val padding = options.paddingPx
        val p = options.prettyPrint

        // "Powered by kUML" branding — the watermark band grows the canvas
        // downward, below the existing bottom padding, so it can never
        // overlap diagram content (same "grow the canvas for chrome"
        // philosophy as the sequence-diagram fragment frame; see CLAUDE.md).
        val watermarkBand = if (options.watermark) WATERMARK_BAND_PX else 0f
        val watermarkFontSize = theme.typography.small.sizePt
        val watermarkTextWidth = WATERMARK_TEXT.length * watermarkFontSize * WATERMARK_CHAR_WIDTH_FACTOR
        val minCanvasWForWatermark = if (options.watermark) watermarkTextWidth + 2 * padding else 0f

        val canvasW = maxOf(layoutResult.canvas.width + 2 * padding, minCanvasWForWatermark)
        val canvasH = layoutResult.canvas.height + 2 * padding + watermarkBand

        val root = StringBuilder()

        if (options.includeXmlDeclaration) {
            root.append("""<?xml version="1.0" encoding="UTF-8"?>""")
            if (p) root.append("\n")
        }

        // Always-on attribution — independent of `embedThemeAsComment` (that
        // flag only gates the theme/engine debug comment below) and of the
        // watermark. Every SVG this project emits — CLI, Gradle plugin, MCP,
        // Markdown/AsciiDoc processors, Web/Desktop UIs — funnels through
        // this function, so this is the single choke point for the
        // "Generated by kUML" metadata comment. (Blueprint diagrams are the
        // one renderer that bypasses this function's `<svg>` assembly
        // entirely — see `renderBlueprintJourney`, which calls
        // [attributionComment] directly to keep the same guarantee.)
        root.append(attributionComment())
        if (p) root.append("\n")

        if (options.embedThemeAsComment) {
            val engineId = layoutResult.engineId.value
            root.append("<!-- kUML SVG · theme: ${theme.name} · engine: $engineId -->")
            if (p) root.append("\n")
        }

        val svgAttrs =
            linkedMapOf(
                "xmlns" to "http://www.w3.org/2000/svg",
                "viewBox" to "0 0 ${fmt(canvasW)} ${fmt(canvasH)}",
                "width" to fmt(canvasW),
                "height" to fmt(canvasH),
            )

        val defsBuilder = SvgBuilder(p, if (p) 2 else 0)
        buildDefs(defsBuilder, theme)

        val nodesBuilder = SvgBuilder(p, if (p) 4 else 0)
        val edgesBuilder = SvgBuilder(p, if (p) 4 else 0)

        // Draw outer diagram frame first (z-order: below all diagram content)
        if (!frameName.isNullOrBlank() && !frameTypeLabel.isNullOrBlank()) {
            renderDiagramFrame(frameTypeLabel, frameName, canvasW, canvasH, nodesBuilder)
        }

        populate(nodesBuilder, edgesBuilder)

        // Assemble <svg>
        val svgAttrsStr = svgAttrs.entries.joinToString(if (p) "\n     " else " ") { (k, v) -> """$k="$v"""" }
        root.append("<svg $svgAttrsStr>")
        if (p) root.append("\n")

        // <defs>
        root.append(if (p) "  <defs>\n" else "<defs>")
        root.append(defsBuilder.toString())
        root.append(if (p) "  </defs>\n" else "</defs>")

        // V3.0.11 — Canvas-Background. Without an explicit rect the SVG is
        // transparent and the host fill (e.g. Obsidian's dark editor pane)
        // shows through between nodes, making diagrams look broken.
        if (options.paintCanvasBackground) {
            val bg = theme.colors.background.toHex()
            val rect = """<rect x="0" y="0" width="${fmt(canvasW)}" height="${fmt(canvasH)}" fill="$bg"/>"""
            root.append(if (p) "  $rect\n" else rect)
        }

        // <g id="nodes">
        root.append(if (p) "  <g id=\"nodes\">\n" else "<g id=\"nodes\">")
        root.append(nodesBuilder.toString())
        root.append(if (p) "  </g>\n" else "</g>")

        // <g id="edges">
        root.append(if (p) "  <g id=\"edges\">\n" else "<g id=\"edges\">")
        root.append(edgesBuilder.toString())
        root.append(if (p) "  </g>\n" else "</g>")

        // "Powered by kUML" branding — drawn last so it is never overpainted
        // by node/edge content. Its baseline sits inside the band added to
        // `canvasH` above, strictly below the content region
        // (`layoutResult.canvas.height + 2 * padding`), so it structurally
        // cannot overlap a node even in the narrow-canvas case (handled by
        // `minCanvasWForWatermark` above). Themed via the smallest/mutedest
        // text role so it reads as unobtrusive chrome, not diagram content.
        if (options.watermark) {
            val ty = theme.typography.small
            val x = fmt(canvasW - padding)
            val y = fmt(canvasH - WATERMARK_GAP_PX)
            // Escape every theme-derived value with the renderer's standard XML
            // utilities, exactly as every other node/text emitter in this module
            // does. `colors.muted.toHex()` is structurally safe (`#RRGGBB`) and
            // `WATERMARK_TEXT` is a compile-time literal, but the theme's
            // `typography.small.family` is a free-form String — escaping it here
            // keeps the choke point injection-proof regardless of where a future
            // theme string originates (defense in depth, same convention as
            // `xmlEscapeAttr`/`xmlEscapeContent` throughout the renderer).
            val fill = xmlEscapeAttr(theme.colors.muted.toHex())
            val family = xmlEscapeAttr(ty.family)
            val text =
                """<text x="$x" y="$y" text-anchor="end" font-family="$family" """ +
                    """font-size="${fmt(ty.sizePt)}" fill="$fill">${xmlEscapeContent(WATERMARK_TEXT)}</text>"""
            root.append(if (p) "  $text\n" else text)
        }

        root.append("</svg>")
        if (p) root.append("\n")

        return root.toString()
    }

    // ── Private helpers ───────────────────────────────────────────────────────

    internal fun buildDefs(
        b: SvgBuilder,
        theme: KumlTheme,
    ) {
        val c = theme.colors
        val ty = theme.typography
        val bo = theme.borders
        // Node fill defaults to the canvas background unless the theme
        // explicitly defines `nodeFill` (e.g. white canvas + tinted nodes).
        val nodeFill = c.effectiveNodeFill.toHex()
        val css =
            buildString {
                append(".kuml-class { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-interface { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-enum { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-component { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-state { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-usecase { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-system { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thickPx}; }\n")
                append(".kuml-container { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thinPx}; }\n")
                append(".kuml-c4component { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thinPx}; }\n")
                // UmlInstanceSpecification (Object Diagram). Ohne diese Regel fielen
                // Instanz-Knoten auf den SVG-Default `fill: black` zurück und überdeckten
                // Header und Slot-Compartment vollständig — derselbe Bug-Typ wie der
                // V3.0.11-Fix für `kuml-action`/`kuml-decision`. Konvention identisch zu
                // `.kuml-class`: Node-Fill + regulärer Border.
                append(".kuml-instance { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                // V0.23.1 — UML Comment/Note. Same fill/border convention as
                // `.kuml-class`; the folded corner ("dog-ear") gets its own class
                // so future themes can style the fold distinctly if desired
                // (e.g. a subtle shadow) without touching the outline stroke.
                append(".kuml-comment { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-comment-fold { fill: none; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thinPx}; }\n")
                append(".kuml-title { font-family: ${ty.title.family}; font-size: ${ty.title.sizePt}px;")
                append(" font-weight: ${ty.title.weight}; fill: ${c.foreground.toHex()}; }\n")
                append(".kuml-title-abstract { font-style: italic; }\n")
                append(".kuml-subtitle { font-family: ${ty.subtitle.family}; font-size: ${ty.subtitle.sizePt}px;")
                append(" font-weight: ${ty.subtitle.weight}; fill: ${c.foreground.toHex()}; }\n")
                append(".kuml-body { font-family: ${ty.body.family}; font-size: ${ty.body.sizePt}px;")
                append(" fill: ${c.foreground.toHex()}; }\n")
                append(".kuml-small { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.muted.toHex()}; }\n")
                // V0.23.2 — Halo for small endpoint labels (multiplicity, role names on
                // association ends, link role names). Mirrors the kuml-edge-label-halo
                // two-pass technique: drawn before the fill text so the background-
                // coloured stroke clears the edge polyline underneath.
                append(".kuml-small-halo { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.background.toHex()}; stroke: ${c.background.toHex()};")
                append(" stroke-width: 3px; stroke-linejoin: round; }\n")
                // V2.0.46 — Edge label: two-pass rendering. `kuml-edge-label-halo` is
                // a thicker stroked version drawn first (renderer emits two <text>
                // elements). Batik's `paint-order: stroke` is unreliable in 1.x — the
                // two-pass approach is the portable trick used since Graphviz.
                append(".kuml-edge-label { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.muted.toHex()}; }\n")
                append(".kuml-edge-label-halo { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.background.toHex()}; stroke: ${c.background.toHex()};")
                append(" stroke-width: 3px; stroke-linejoin: round; }\n")
                append(".kuml-stereotype { font-family: ${ty.stereotype.family};")
                append(" font-size: ${ty.stereotype.sizePt}px; font-style: italic;")
                append(" fill: ${c.muted.toHex()}; }\n")
                // V0.27.1 — Halo for edge-mid stereotype labels (e.g. `«FK»` on an
                // association). Without this, the label sits directly on the edge
                // polyline with no background contrast — the line visually cuts
                // through the italic glyphs. Mirrors the kuml-edge-label-halo
                // two-pass technique: renderEdgeStereotype() emits this class first,
                // then the fill copy. Not used for in-box header/feature stereotypes
                // (renderHeader, featureStereotypeTspan) — those never sit on a line.
                append(".kuml-stereotype-halo { font-family: ${ty.stereotype.family};")
                append(" font-size: ${ty.stereotype.sizePt}px; font-style: italic;")
                append(" fill: ${c.background.toHex()}; stroke: ${c.background.toHex()};")
                append(" stroke-width: 3px; stroke-linejoin: round; }\n")
                // V1.1: tagged-value compartment text — slightly smaller than body, italic
                val tvFontSize = theme.stereotypes.taggedValueFontSize
                append(".kuml-tagged-value { font-family: ${ty.body.family};")
                append(" font-size: ${tvFontSize}px; font-style: italic;")
                append(" fill: ${c.muted.toHex()}; }\n")
                append(".kuml-edge { stroke: ${c.edge.toHex()}; stroke-width: ${bo.regularPx}; fill: none; }\n")
                // Sequence diagram filled arrowhead (SYNC_CALL / CREATE). A separate class
                // is required because `.kuml-edge { fill: none }` has higher CSS specificity
                // than SVG presentation attributes, so `fill="currentColor"` on the polygon
                // would be overridden. This class explicitly sets fill to the edge colour.
                append(".kuml-seq-arrow-filled { stroke: ${c.edge.toHex()}; stroke-width: ${bo.regularPx}; fill: ${c.edge.toHex()}; }\n")
                append(
                    ".kuml-edge-dashed { stroke: ${c.edgeMuted.toHex()}; stroke-width: ${bo.regularPx};" +
                        " fill: none; stroke-dasharray: 8 4; }\n",
                )
                append(".kuml-divider { stroke: ${c.border.toHex()}; stroke-width: ${bo.thinPx}; }\n")
                append(".kuml-actor { stroke: ${c.foreground.toHex()}; stroke-width: ${bo.regularPx}; fill: none; }\n")
                append(".kuml-frame { fill: none; stroke: ${c.border.toHex()}; stroke-width: ${bo.regularPx}; }\n")
                // V2.0.44 — UmlCollaboration is rendered as an outlined ellipse (UML 2.5 §11.7.1).
                // Without an explicit `fill: none` here Batik defaults to black-fill, swallowing
                // the text. The dashed-stroke pattern is supplied per-element via stroke-dasharray.
                append(".kuml-collaboration { fill: none; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                // V2.0.44 — UML 2.x port glyph: filled square on the component border.
                // Label uses small body font, foreground colour.
                append(".kuml-port { fill: ${c.foreground.toHex()}; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thinPx}; }\n")
                append(".kuml-port-label { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.foreground.toHex()}; }\n")
                // Halo class: white stroke drawn before the fill copy of port labels so that
                // connector polylines behind the label don't bleed through. Uses two sibling
                // <text> elements (halo first, label second) because paint-order is not
                // supported by all SVG renderers (e.g. Batik used for PNG export).
                append(".kuml-port-label-halo { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: none; stroke: ${c.background.toHex()}; stroke-width: 3.5px; stroke-linejoin: round; }\n")
                // V3.x — UML 2.x Composite-Structure internal connector (delegation or assembly).
                // Drawn as a plain line inside the parent component's local frame — no ELK routing.
                // Uses the same stroke style as a kuml-divider (thin, border colour) so it blends
                // with the composite-structure visual language. Label uses the small body font.
                append(".kuml-connector { fill: none; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-connector-label { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.foreground.toHex()}; }\n")
                // V3.0.11 — UML-Activity-Diagramm (Action-Box, Decision-Raute, Fork/Join-Bar,
                // Initial-/Final-Marker). Diese Klassen werden in `UmlV11Svg.renderUmlActivityNode`
                // referenziert; ohne CSS-Regel renderten SVG-Konsumenten alle Shapes mit
                // `fill: black` (SVG-Default) — Action-Text und Decision-Label wurden vollständig
                // verschluckt, Edges sahen aus, als endeten sie im Nichts (Arrowhead vom
                // schwarzen Fill verdeckt). Konventionen:
                //  - kuml-action / kuml-decision: wie `.kuml-class` — Hintergrund-Fill + Border.
                //  - kuml-fork-bar / kuml-pseudostate: gefüllter Balken / gefüllter Initial-
                //    Marker (kanonische UML-Notation: Initial-Knoten ist ein vollgefüllter
                //    Punkt, Fork/Join eine massive Synchronisations-Bar).
                //  - kuml-final-outer: Donut-Außenring — Hintergrund-Fill, damit der
                //    gefüllte innere Pseudostate-Kreis als Ring erkennbar bleibt.
                append(".kuml-action { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-decision { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-fork-bar { fill: ${c.foreground.toHex()}; stroke: ${c.foreground.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-pseudostate { fill: ${c.foreground.toHex()}; stroke: ${c.foreground.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-final-outer { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                // V1.1 — UML-Deployment-Diagramm (Node-Würfel, Artifact, Stereotype-Box)
                // und UML-Timing-Diagramm (Lifeline-Frame, Step-Line). Diese Klassen werden
                // in `UmlV11Svg.kt` referenziert; ohne CSS-Regel rendern SVG-Konsumenten alle
                // Shapes mit `fill: black` (SVG-Default) — identischer Bug-Typ wie V3.0.11
                // (kuml-action/kuml-decision) und kuml-instance.
                // Konventionen:
                //  - kuml-node (Frontfläche) / kuml-artifact / kuml-stereotype-box:
                //    Hintergrund-Fill + regulärer Border — wie .kuml-class.
                //  - kuml-node-top / kuml-node-side (3D-Akzentflächen des Würfels):
                //    gedämpfte Fill (c.muted) für leichten Tiefeneffekt, gleicher Border.
                //  - kuml-artifact-ear (Eselsecke): gedämpfte Fill als Kontrast zur Hauptfläche.
                //  - kuml-timing-frame: Hintergrund-Fill + Border (Rahmen der Lifeline).
                //  - kuml-timing-line: Kanten-Stroke ohne Fill (Zustandswechsel-Pfad).
                append(".kuml-node { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-node-top { fill: ${c.muted.toHex()}; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-node-side { fill: ${c.muted.toHex()}; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-artifact { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-artifact-ear { fill: ${c.muted.toHex()}; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-stereotype-box { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-timing-frame { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-timing-line { stroke: ${c.edge.toHex()}; stroke-width: ${bo.regularPx}; fill: none; }\n")
                // V3.4.2 — ERM/Martin (crow's-foot) renderer. Entity boxes reuse the
                // `.kuml-class` fill/border convention (see kuml-erm-entity below);
                // dedicated classes only exist where ERM needs a visual distinct from
                // UML class diagrams (weak-entity double border, view dashed outline,
                // PK underline, cardinality glyphs).
                append(".kuml-erm-entity { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-entity-inner { fill: none; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thinPx}; }\n")
                append(".kuml-erm-view { fill: $nodeFill; stroke: ${c.muted.toHex()};")
                append(" stroke-width: ${bo.regularPx}; stroke-dasharray: 6 3; }\n")
                append(".kuml-erm-view-query { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" font-style: italic; fill: ${c.muted.toHex()}; }\n")
                append(".kuml-erm-marker { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" font-weight: bold; fill: ${c.muted.toHex()}; }\n")
                append(".kuml-erm-default { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" font-style: italic; fill: ${c.muted.toHex()}; }\n")
                append(".kuml-erm-index { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" font-style: italic; fill: ${c.muted.toHex()}; }\n")
                append(".kuml-erm-pk-underline { stroke: ${c.foreground.toHex()}; stroke-width: ${bo.thinPx}; }\n")
                append(".kuml-erm-crowfoot { fill: none; stroke: ${c.edge.toHex()}; stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-optional-marker { fill: $nodeFill; stroke: ${c.edge.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-mandatory-marker { stroke: ${c.edge.toHex()}; stroke-width: ${bo.regularPx}; }\n")
                // V3.4.3 — ERM/Bachman renderer. Entity boxes and the hollow
                // `.kuml-erm-optional-marker` circle above are reused as-is;
                // only the arrowhead and the filled mandatory circle are
                // Bachman-specific (the crow's-foot/bar equivalents differ
                // visually enough to need dedicated classes).
                append(".kuml-erm-bachman-arrow { fill: ${c.edge.toHex()}; stroke: ${c.edge.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-bachman-mandatory { fill: ${c.edge.toHex()}; stroke: ${c.edge.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                // V3.4.4 — ERM/Chen renderer. Entities reuse `.kuml-erm-entity` /
                // `.kuml-erm-entity-inner` (title-only box, weak-entity double
                // border) and the PK underline / plain `.kuml-edge` line from
                // above; attribute ovals and relationship diamonds are new
                // shapes with no Martin/Bachman equivalent.
                append(".kuml-erm-chen-attribute { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-chen-relationship { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-chen-relationship-inner { fill: none; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.thinPx}; }\n")
                // Bug-fix (fix/erm-chen-label-collisions, V3.4.7): cardinality
                // labels used to have their own `.kuml-erm-chen-cardinality`
                // class with no halo pass. They now route through
                // `ErmEdgeLabels.renderErmCardinalityLabel` -> `renderEdgeLabelWithHalo`,
                // reusing the `.kuml-edge-label` / `.kuml-edge-label-halo` rules
                // above (same styling every other ERM edge label uses).
                // V3.4.5 — ERM/IDEF1X renderer. Entities reuse `.kuml-erm-entity`
                // (now optionally rounded via `rx`/`ry`) and the plain
                // `.kuml-edge` / `.kuml-edge-dashed` lines from above; the
                // child-end dot, parent-end diamond, cardinality annotation,
                // and category discriminator circle/completeness bars are new.
                append(".kuml-erm-idef1x-dot { fill: ${c.edge.toHex()}; stroke: ${c.edge.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-idef1x-diamond { fill: $nodeFill; stroke: ${c.edge.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-idef1x-card { font-family: ${ty.small.family}; font-size: ${ty.small.sizePt}px;")
                append(" fill: ${c.foreground.toHex()}; }\n")
                append(".kuml-erm-idef1x-category { fill: $nodeFill; stroke: ${c.border.toHex()};")
                append(" stroke-width: ${bo.regularPx}; }\n")
                append(".kuml-erm-idef1x-completeness { stroke: ${c.border.toHex()}; stroke-width: ${bo.regularPx}; }\n")
            }

        b.tag("style") {
            text(css)
        }

        // Arrow markers have been replaced by inline geometry rendered directly
        // adjacent to each edge via SvgInlineArrow.kt. The former <marker>/url(#id)
        // approach failed in Obsidian reading mode because DOMParser + appendChild
        // does not reliably register <defs> IDs in the host HTML document's ID table
        // (Electron adoption bug), causing arrowheads to silently disappear.
    }

    private fun fmt(v: Float): String = fmt2(v)
}
