package dev.kuml.cli

import dev.kuml.cli.structurizr.KumlDslGenerator
import dev.kuml.cli.structurizr.StructurizrElement
import dev.kuml.cli.structurizr.StructurizrModel
import dev.kuml.cli.structurizr.StructurizrRelationship
import dev.kuml.cli.structurizr.StructurizrView
import dev.kuml.cli.structurizr.StructurizrViews
import dev.kuml.cli.structurizr.StructurizrWorkspace
import io.kotest.core.spec.style.FunSpec
import io.kotest.matchers.string.shouldContain
import io.kotest.matchers.string.shouldNotContain

class KumlDslGeneratorTest :
    FunSpec({

        fun emptyWorkspace(name: String = "Test") =
            StructurizrWorkspace(
                name = name,
                description = null,
                model = StructurizrModel(emptyList(), emptyList()),
                views = StructurizrViews(),
            )

        // 1. Generate empty model
        test("generate empty model produces valid scaffold") {
            val workspace = emptyWorkspace("MyApp")
            val output = KumlDslGenerator.generate(workspace, "workspace.dsl")

            output shouldContain "// Generated by kuml import --format structurizr"
            output shouldContain "// Source: workspace.dsl"
            output shouldContain "import dev.kuml.c4.dsl.*"
            output shouldContain "import dev.kuml.c4.model.*"
            output shouldContain "c4Model(\"MyApp\")"
            output shouldContain "}"
        }

        // 2. Generate model with persons and systems
        test("generate model with persons and systems") {
            val workspace =
                StructurizrWorkspace(
                    name = "Banking",
                    description = null,
                    model =
                        StructurizrModel(
                            elements =
                                listOf(
                                    StructurizrElement.Person(
                                        identifier = "customer",
                                        name = "Customer",
                                        description = "A bank customer",
                                        external = false,
                                    ),
                                    StructurizrElement.SoftwareSystem(
                                        identifier = "banking",
                                        name = "Banking System",
                                        description = "Core banking",
                                        external = false,
                                    ),
                                    StructurizrElement.SoftwareSystem(
                                        identifier = "mainframe",
                                        name = "Mainframe",
                                        description = null,
                                        external = true,
                                    ),
                                ),
                            relationships = emptyList(),
                        ),
                    views = StructurizrViews(),
                )

            val output = KumlDslGenerator.generate(workspace, "test.dsl")

            output shouldContain "val customer = person(\"Customer\")"
            output shouldContain "description = \"A bank customer\""
            output shouldContain "val banking = softwareSystem(\"Banking System\")"
            output shouldContain "val mainframe = softwareSystem(\"Mainframe\")"
            output shouldContain "external = true"
            // No unnecessary external = false
            output shouldNotContain "external = false"
        }

        // 3. Generate model with containers and components (test var pre-declarations)
        test("generate model with containers pre-declares nullable vars") {
            val workspace =
                StructurizrWorkspace(
                    name = "Sys",
                    description = null,
                    model =
                        StructurizrModel(
                            elements =
                                listOf(
                                    StructurizrElement.SoftwareSystem(
                                        identifier = "sys",
                                        name = "My System",
                                        description = null,
                                        containers =
                                            listOf(
                                                StructurizrElement.Container(
                                                    identifier = "webApp",
                                                    name = "Web App",
                                                    description = "Front-end",
                                                    technology = "React",
                                                    system = "sys",
                                                    components =
                                                        listOf(
                                                            StructurizrElement.Component(
                                                                identifier = "authCtrl",
                                                                name = "Auth Controller",
                                                                description = "Handles auth",
                                                                technology = "Spring MVC",
                                                                container = "webApp",
                                                            ),
                                                        ),
                                                ),
                                            ),
                                    ),
                                ),
                            relationships = emptyList(),
                        ),
                    views = StructurizrViews(),
                )

            val output = KumlDslGenerator.generate(workspace, "test.dsl")

            // Nullable pre-declarations must appear BEFORE c4Model block
            val preDeclarationsEnd = output.indexOf("c4Model(")
            val webAppDecl = output.indexOf("var webApp: C4Container? = null")
            val authCtrlDecl = output.indexOf("var authCtrl: C4Component? = null")

            assert(webAppDecl >= 0) { "Expected var webApp pre-declaration" }
            assert(authCtrlDecl >= 0) { "Expected var authCtrl pre-declaration" }
            assert(webAppDecl < preDeclarationsEnd) { "webApp declaration must be before c4Model block" }
            assert(authCtrlDecl < preDeclarationsEnd) { "authCtrl declaration must be before c4Model block" }

            output shouldContain "technology = \"React\""
            output shouldContain "technology = \"Spring MVC\""
        }

        // 4. Generate model with relationships (including nullable container refs with !!)
        test("generate model with relationships uses !! for nullable container vars") {
            val workspace =
                StructurizrWorkspace(
                    name = "Bank",
                    description = null,
                    model =
                        StructurizrModel(
                            elements =
                                listOf(
                                    StructurizrElement.Person(
                                        identifier = "customer",
                                        name = "Customer",
                                        description = null,
                                    ),
                                    StructurizrElement.SoftwareSystem(
                                        identifier = "banking",
                                        name = "Banking System",
                                        description = null,
                                        containers =
                                            listOf(
                                                StructurizrElement.Container(
                                                    identifier = "webApp",
                                                    name = "Web App",
                                                    description = null,
                                                    technology = "React",
                                                    system = "banking",
                                                ),
                                            ),
                                    ),
                                ),
                            relationships =
                                listOf(
                                    // person -> system: both are val, no !!
                                    StructurizrRelationship("customer", "banking", "Uses", "HTTPS"),
                                    // container -> something: container is nullable var, needs !!
                                    StructurizrRelationship("webApp", "banking", "Calls API", null),
                                ),
                        ),
                    views = StructurizrViews(),
                )

            val output = KumlDslGenerator.generate(workspace, "test.dsl")

            // Direct val references — no !!
            output shouldContain "relationship(customer, banking)"
            // Nullable container reference — must use !!
            output shouldContain "relationship(webApp!!, banking)"
        }

        // 5. Generate model with views
        test("generate model with explicit views emits diagram calls") {
            val workspace =
                StructurizrWorkspace(
                    name = "ViewsTest",
                    description = null,
                    model =
                        StructurizrModel(
                            elements =
                                listOf(
                                    StructurizrElement.SoftwareSystem(
                                        identifier = "sys",
                                        name = "System",
                                        description = null,
                                    ),
                                ),
                            relationships = emptyList(),
                        ),
                    views =
                        StructurizrViews(
                            views =
                                listOf(
                                    StructurizrView.SystemContext("sys", "Context", "System Context diagram"),
                                    StructurizrView.Container("sys", "Containers", "Container diagram"),
                                    StructurizrView.SystemLandscape("Landscape", "All systems"),
                                    StructurizrView.Deployment("Production", "Deploy", "Deployment diagram"),
                                    StructurizrView.Component("webApp", "Components", null),
                                ),
                        ),
                )

            val output = KumlDslGenerator.generate(workspace, "test.dsl")

            output shouldContain "systemContextDiagram("
            output shouldContain "containerDiagram("
            output shouldContain "systemLandscapeDiagram("
            output shouldContain "deploymentDiagram("
            output shouldContain "componentDiagram("
        }

        // 6. No views → auto-generate default diagrams
        test("generate model without views auto-generates system context diagrams") {
            val workspace =
                StructurizrWorkspace(
                    name = "Auto",
                    description = null,
                    model =
                        StructurizrModel(
                            elements =
                                listOf(
                                    StructurizrElement.SoftwareSystem(
                                        identifier = "sys",
                                        name = "My System",
                                        description = null,
                                        containers =
                                            listOf(
                                                StructurizrElement.Container(
                                                    identifier = "c1",
                                                    name = "Container",
                                                    description = null,
                                                    technology = null,
                                                    system = "sys",
                                                ),
                                            ),
                                    ),
                                ),
                            relationships = emptyList(),
                        ),
                    views = StructurizrViews(views = emptyList()),
                )

            val output = KumlDslGenerator.generate(workspace, "test.dsl")

            output shouldContain "systemContextDiagram(\"My System\")"
            // Has containers, so also a container diagram
            output shouldContain "containerDiagram("
        }

        // 7. Unknown relationship identifier → emitted as TODO comment
        test("generate relationship with unknown identifier emits TODO comment") {
            val workspace =
                StructurizrWorkspace(
                    name = "Unknown",
                    description = null,
                    model =
                        StructurizrModel(
                            elements =
                                listOf(
                                    StructurizrElement.Person(identifier = "user", name = "User", description = null),
                                ),
                            relationships =
                                listOf(
                                    StructurizrRelationship("user", "unknownSystem", "Uses", null),
                                ),
                        ),
                    views = StructurizrViews(),
                )

            val output = KumlDslGenerator.generate(workspace, "test.dsl")

            output shouldContain "// TODO: relationship user -> unknownSystem"
        }
    })
